-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.COLUMNPARAMETERTYPE = protobuf.EnumDescriptor()
module.COLUMNPARAMETERTYPE_UNDEFINED_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_INT_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_DOUBLE_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_INT64_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_CACHED_STRING_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_TIME_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_DATE_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.COLUMNPARAMETERTYPE_QTABLE_STRING_TYPE_ENUM = protobuf.EnumValueDescriptor()
module.REQUEST = protobuf.Descriptor()
module.REQUEST_T_ID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_ICODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_NAME_FIELD = protobuf.FieldDescriptor()
module.REQUEST_IS_DEFAULT_FIELD = protobuf.FieldDescriptor()
module.REQUEST_PAR_TYPE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_WIDTH_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.COLUMNPARAMETERTYPE_UNDEFINED_ENUM.name = 'UNDEFINED'
module.COLUMNPARAMETERTYPE_UNDEFINED_ENUM.index = 0
module.COLUMNPARAMETERTYPE_UNDEFINED_ENUM.number = 0
module.COLUMNPARAMETERTYPE_QTABLE_INT_TYPE_ENUM.name = 'QTABLE_INT_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_INT_TYPE_ENUM.index = 1
module.COLUMNPARAMETERTYPE_QTABLE_INT_TYPE_ENUM.number = 1
module.COLUMNPARAMETERTYPE_QTABLE_DOUBLE_TYPE_ENUM.name = 'QTABLE_DOUBLE_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_DOUBLE_TYPE_ENUM.index = 2
module.COLUMNPARAMETERTYPE_QTABLE_DOUBLE_TYPE_ENUM.number = 2
module.COLUMNPARAMETERTYPE_QTABLE_INT64_TYPE_ENUM.name = 'QTABLE_INT64_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_INT64_TYPE_ENUM.index = 3
module.COLUMNPARAMETERTYPE_QTABLE_INT64_TYPE_ENUM.number = 3
module.COLUMNPARAMETERTYPE_QTABLE_CACHED_STRING_TYPE_ENUM.name = 'QTABLE_CACHED_STRING_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_CACHED_STRING_TYPE_ENUM.index = 4
module.COLUMNPARAMETERTYPE_QTABLE_CACHED_STRING_TYPE_ENUM.number = 4
module.COLUMNPARAMETERTYPE_QTABLE_TIME_TYPE_ENUM.name = 'QTABLE_TIME_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_TIME_TYPE_ENUM.index = 5
module.COLUMNPARAMETERTYPE_QTABLE_TIME_TYPE_ENUM.number = 5
module.COLUMNPARAMETERTYPE_QTABLE_DATE_TYPE_ENUM.name = 'QTABLE_DATE_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_DATE_TYPE_ENUM.index = 6
module.COLUMNPARAMETERTYPE_QTABLE_DATE_TYPE_ENUM.number = 6
module.COLUMNPARAMETERTYPE_QTABLE_STRING_TYPE_ENUM.name = 'QTABLE_STRING_TYPE'
module.COLUMNPARAMETERTYPE_QTABLE_STRING_TYPE_ENUM.index = 7
module.COLUMNPARAMETERTYPE_QTABLE_STRING_TYPE_ENUM.number = 7
module.COLUMNPARAMETERTYPE.name = 'ColumnParameterType'
module.COLUMNPARAMETERTYPE.full_name = '.qlua.rpc.AddColumn.ColumnParameterType'
module.COLUMNPARAMETERTYPE.values = {module.COLUMNPARAMETERTYPE_UNDEFINED_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_INT_TYPE_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_DOUBLE_TYPE_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_INT64_TYPE_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_CACHED_STRING_TYPE_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_TIME_TYPE_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_DATE_TYPE_ENUM,module.COLUMNPARAMETERTYPE_QTABLE_STRING_TYPE_ENUM}
module.REQUEST_T_ID_FIELD.name = 't_id'
module.REQUEST_T_ID_FIELD.full_name = '.qlua.rpc.AddColumn.Request.t_id'
module.REQUEST_T_ID_FIELD.number = 1
module.REQUEST_T_ID_FIELD.index = 0
module.REQUEST_T_ID_FIELD.label = 1
module.REQUEST_T_ID_FIELD.has_default_value = false
module.REQUEST_T_ID_FIELD.default_value = 0
module.REQUEST_T_ID_FIELD.type = 5
module.REQUEST_T_ID_FIELD.cpp_type = 1

module.REQUEST_ICODE_FIELD.name = 'icode'
module.REQUEST_ICODE_FIELD.full_name = '.qlua.rpc.AddColumn.Request.icode'
module.REQUEST_ICODE_FIELD.number = 2
module.REQUEST_ICODE_FIELD.index = 1
module.REQUEST_ICODE_FIELD.label = 1
module.REQUEST_ICODE_FIELD.has_default_value = false
module.REQUEST_ICODE_FIELD.default_value = 0
module.REQUEST_ICODE_FIELD.type = 5
module.REQUEST_ICODE_FIELD.cpp_type = 1

module.REQUEST_NAME_FIELD.name = 'name'
module.REQUEST_NAME_FIELD.full_name = '.qlua.rpc.AddColumn.Request.name'
module.REQUEST_NAME_FIELD.number = 3
module.REQUEST_NAME_FIELD.index = 2
module.REQUEST_NAME_FIELD.label = 1
module.REQUEST_NAME_FIELD.has_default_value = false
module.REQUEST_NAME_FIELD.default_value = ''
module.REQUEST_NAME_FIELD.type = 9
module.REQUEST_NAME_FIELD.cpp_type = 9

module.REQUEST_IS_DEFAULT_FIELD.name = 'is_default'
module.REQUEST_IS_DEFAULT_FIELD.full_name = '.qlua.rpc.AddColumn.Request.is_default'
module.REQUEST_IS_DEFAULT_FIELD.number = 4
module.REQUEST_IS_DEFAULT_FIELD.index = 3
module.REQUEST_IS_DEFAULT_FIELD.label = 1
module.REQUEST_IS_DEFAULT_FIELD.has_default_value = false
module.REQUEST_IS_DEFAULT_FIELD.default_value = false
module.REQUEST_IS_DEFAULT_FIELD.type = 8
module.REQUEST_IS_DEFAULT_FIELD.cpp_type = 7

module.REQUEST_PAR_TYPE_FIELD.name = 'par_type'
module.REQUEST_PAR_TYPE_FIELD.full_name = '.qlua.rpc.AddColumn.Request.par_type'
module.REQUEST_PAR_TYPE_FIELD.number = 5
module.REQUEST_PAR_TYPE_FIELD.index = 4
module.REQUEST_PAR_TYPE_FIELD.label = 1
module.REQUEST_PAR_TYPE_FIELD.has_default_value = false
module.REQUEST_PAR_TYPE_FIELD.default_value = nil
module.REQUEST_PAR_TYPE_FIELD.enum_type = module.COLUMNPARAMETERTYPE
module.REQUEST_PAR_TYPE_FIELD.type = 14
module.REQUEST_PAR_TYPE_FIELD.cpp_type = 8

module.REQUEST_WIDTH_FIELD.name = 'width'
module.REQUEST_WIDTH_FIELD.full_name = '.qlua.rpc.AddColumn.Request.width'
module.REQUEST_WIDTH_FIELD.number = 6
module.REQUEST_WIDTH_FIELD.index = 5
module.REQUEST_WIDTH_FIELD.label = 1
module.REQUEST_WIDTH_FIELD.has_default_value = false
module.REQUEST_WIDTH_FIELD.default_value = 0
module.REQUEST_WIDTH_FIELD.type = 5
module.REQUEST_WIDTH_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.AddColumn.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_T_ID_FIELD, module.REQUEST_ICODE_FIELD, module.REQUEST_NAME_FIELD, module.REQUEST_IS_DEFAULT_FIELD, module.REQUEST_PAR_TYPE_FIELD, module.REQUEST_WIDTH_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.AddColumn.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = 0
module.RESULT_RESULT_FIELD.type = 5
module.RESULT_RESULT_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.AddColumn.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.ColumnParameterType = {}
module.ColumnParameterType.QTABLE_CACHED_STRING_TYPE = 4
module.ColumnParameterType.QTABLE_DATE_TYPE = 6
module.ColumnParameterType.QTABLE_DOUBLE_TYPE = 2
module.ColumnParameterType.QTABLE_INT64_TYPE = 3
module.ColumnParameterType.QTABLE_INT_TYPE = 1
module.ColumnParameterType.QTABLE_STRING_TYPE = 7
module.ColumnParameterType.QTABLE_TIME_TYPE = 5
module.ColumnParameterType.UNDEFINED = 0
module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {'ColumnParameterType'}

return module
