-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.REQUEST = protobuf.Descriptor()
module.REQUEST_LABELPARAMSENTRY = protobuf.Descriptor()
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD = protobuf.FieldDescriptor()
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CHART_TAG_FIELD = protobuf.FieldDescriptor()
module.REQUEST_LABEL_PARAMS_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_LABEL_ID_FIELD = protobuf.FieldDescriptor()

module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.name = 'key'
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.full_name = '.qlua.rpc.AddLabel.Request.LabelParamsEntry.key'
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.number = 1
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.index = 0
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.label = 1
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.has_default_value = false
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.default_value = ''
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.type = 9
module.REQUEST_LABELPARAMSENTRY_KEY_FIELD.cpp_type = 9

module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.name = 'value'
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.full_name = '.qlua.rpc.AddLabel.Request.LabelParamsEntry.value'
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.number = 2
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.index = 1
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.label = 1
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.has_default_value = false
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.default_value = ''
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.type = 9
module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD.cpp_type = 9

module.REQUEST_LABELPARAMSENTRY.name = 'LabelParamsEntry'
module.REQUEST_LABELPARAMSENTRY.full_name = '.qlua.rpc.AddLabel.Request.LabelParamsEntry'
module.REQUEST_LABELPARAMSENTRY.nested_types = {}
module.REQUEST_LABELPARAMSENTRY.enum_types = {}
module.REQUEST_LABELPARAMSENTRY.fields = {module.REQUEST_LABELPARAMSENTRY_KEY_FIELD, module.REQUEST_LABELPARAMSENTRY_VALUE_FIELD}
module.REQUEST_LABELPARAMSENTRY.is_extendable = false
module.REQUEST_LABELPARAMSENTRY.extensions = {}
module.REQUEST_LABELPARAMSENTRY.containing_type = REQUEST
module.REQUEST_CHART_TAG_FIELD.name = 'chart_tag'
module.REQUEST_CHART_TAG_FIELD.full_name = '.qlua.rpc.AddLabel.Request.chart_tag'
module.REQUEST_CHART_TAG_FIELD.number = 1
module.REQUEST_CHART_TAG_FIELD.index = 0
module.REQUEST_CHART_TAG_FIELD.label = 1
module.REQUEST_CHART_TAG_FIELD.has_default_value = false
module.REQUEST_CHART_TAG_FIELD.default_value = ''
module.REQUEST_CHART_TAG_FIELD.type = 9
module.REQUEST_CHART_TAG_FIELD.cpp_type = 9

module.REQUEST_LABEL_PARAMS_FIELD.name = 'label_params'
module.REQUEST_LABEL_PARAMS_FIELD.full_name = '.qlua.rpc.AddLabel.Request.label_params'
module.REQUEST_LABEL_PARAMS_FIELD.number = 2
module.REQUEST_LABEL_PARAMS_FIELD.index = 1
module.REQUEST_LABEL_PARAMS_FIELD.label = 3
module.REQUEST_LABEL_PARAMS_FIELD.has_default_value = false
module.REQUEST_LABEL_PARAMS_FIELD.default_value = {}
module.REQUEST_LABEL_PARAMS_FIELD.message_type = module.REQUEST_LABELPARAMSENTRY
module.REQUEST_LABEL_PARAMS_FIELD.type = 11
module.REQUEST_LABEL_PARAMS_FIELD.cpp_type = 10

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.AddLabel.Request'
module.REQUEST.nested_types = {module.REQUEST_LABELPARAMSENTRY}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CHART_TAG_FIELD, module.REQUEST_LABEL_PARAMS_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_LABEL_ID_FIELD.name = 'label_id'
module.RESULT_LABEL_ID_FIELD.full_name = '.qlua.rpc.AddLabel.Result.label_id'
module.RESULT_LABEL_ID_FIELD.number = 1
module.RESULT_LABEL_ID_FIELD.index = 0
module.RESULT_LABEL_ID_FIELD.label = 1
module.RESULT_LABEL_ID_FIELD.has_default_value = false
module.RESULT_LABEL_ID_FIELD.default_value = 0
module.RESULT_LABEL_ID_FIELD.type = 5
module.RESULT_LABEL_ID_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.AddLabel.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_LABEL_ID_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Request.LabelParamsEntry = protobuf.Message(module.REQUEST_LABELPARAMSENTRY)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
