-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.RESULT = protobuf.Descriptor()
module.RESULT_T_ID_FIELD = protobuf.FieldDescriptor()

module.RESULT_T_ID_FIELD.name = 't_id'
module.RESULT_T_ID_FIELD.full_name = '.qlua.rpc.AllocTable.Result.t_id'
module.RESULT_T_ID_FIELD.number = 1
module.RESULT_T_ID_FIELD.index = 0
module.RESULT_T_ID_FIELD.label = 1
module.RESULT_T_ID_FIELD.has_default_value = false
module.RESULT_T_ID_FIELD.default_value = 0
module.RESULT_T_ID_FIELD.type = 5
module.RESULT_T_ID_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.AllocTable.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_T_ID_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Result'}
module.ENUM_TYPES = {}

return module
