-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

local imports = {}
imports['qlua/rpc/qlua_structures_pb'] = require 'qlua/rpc/qlua_structures_pb'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_TAG_FIELD = protobuf.FieldDescriptor()
module.REQUEST_LINE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_FIRST_CANDLE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_COUNT_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_T_FIELD = protobuf.FieldDescriptor()
module.RESULT_N_FIELD = protobuf.FieldDescriptor()
module.RESULT_L_FIELD = protobuf.FieldDescriptor()

module.REQUEST_TAG_FIELD.name = 'tag'
module.REQUEST_TAG_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Request.tag'
module.REQUEST_TAG_FIELD.number = 1
module.REQUEST_TAG_FIELD.index = 0
module.REQUEST_TAG_FIELD.label = 1
module.REQUEST_TAG_FIELD.has_default_value = false
module.REQUEST_TAG_FIELD.default_value = ''
module.REQUEST_TAG_FIELD.type = 9
module.REQUEST_TAG_FIELD.cpp_type = 9

module.REQUEST_LINE_FIELD.name = 'line'
module.REQUEST_LINE_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Request.line'
module.REQUEST_LINE_FIELD.number = 2
module.REQUEST_LINE_FIELD.index = 1
module.REQUEST_LINE_FIELD.label = 1
module.REQUEST_LINE_FIELD.has_default_value = false
module.REQUEST_LINE_FIELD.default_value = 0
module.REQUEST_LINE_FIELD.type = 5
module.REQUEST_LINE_FIELD.cpp_type = 1

module.REQUEST_FIRST_CANDLE_FIELD.name = 'first_candle'
module.REQUEST_FIRST_CANDLE_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Request.first_candle'
module.REQUEST_FIRST_CANDLE_FIELD.number = 3
module.REQUEST_FIRST_CANDLE_FIELD.index = 2
module.REQUEST_FIRST_CANDLE_FIELD.label = 1
module.REQUEST_FIRST_CANDLE_FIELD.has_default_value = false
module.REQUEST_FIRST_CANDLE_FIELD.default_value = 0
module.REQUEST_FIRST_CANDLE_FIELD.type = 5
module.REQUEST_FIRST_CANDLE_FIELD.cpp_type = 1

module.REQUEST_COUNT_FIELD.name = 'count'
module.REQUEST_COUNT_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Request.count'
module.REQUEST_COUNT_FIELD.number = 4
module.REQUEST_COUNT_FIELD.index = 3
module.REQUEST_COUNT_FIELD.label = 1
module.REQUEST_COUNT_FIELD.has_default_value = false
module.REQUEST_COUNT_FIELD.default_value = 0
module.REQUEST_COUNT_FIELD.type = 5
module.REQUEST_COUNT_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getCandlesByIndex.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_TAG_FIELD, module.REQUEST_LINE_FIELD, module.REQUEST_FIRST_CANDLE_FIELD, module.REQUEST_COUNT_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_T_FIELD.name = 't'
module.RESULT_T_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Result.t'
module.RESULT_T_FIELD.number = 1
module.RESULT_T_FIELD.index = 0
module.RESULT_T_FIELD.label = 3
module.RESULT_T_FIELD.has_default_value = false
module.RESULT_T_FIELD.default_value = {}
module.RESULT_T_FIELD.message_type = imports['qlua/rpc/qlua_structures_pb'].CANDLEENTRY
module.RESULT_T_FIELD.type = 11
module.RESULT_T_FIELD.cpp_type = 10

module.RESULT_N_FIELD.name = 'n'
module.RESULT_N_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Result.n'
module.RESULT_N_FIELD.number = 2
module.RESULT_N_FIELD.index = 1
module.RESULT_N_FIELD.label = 1
module.RESULT_N_FIELD.has_default_value = false
module.RESULT_N_FIELD.default_value = 0
module.RESULT_N_FIELD.type = 5
module.RESULT_N_FIELD.cpp_type = 1

module.RESULT_L_FIELD.name = 'l'
module.RESULT_L_FIELD.full_name = '.qlua.rpc.getCandlesByIndex.Result.l'
module.RESULT_L_FIELD.number = 3
module.RESULT_L_FIELD.index = 2
module.RESULT_L_FIELD.label = 1
module.RESULT_L_FIELD.has_default_value = false
module.RESULT_L_FIELD.default_value = ''
module.RESULT_L_FIELD.type = 9
module.RESULT_L_FIELD.cpp_type = 9

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getCandlesByIndex.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_T_FIELD, module.RESULT_N_FIELD, module.RESULT_L_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
