-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

local imports = {}
imports['qlua/rpc/qlua_structures_pb'] = require 'qlua/rpc/qlua_structures_pb'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_FIRMID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CLIENT_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_SEC_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TRDACCID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_LIMIT_KIND_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_DEPO_EX_FIELD = protobuf.FieldDescriptor()

module.REQUEST_FIRMID_FIELD.name = 'firmid'
module.REQUEST_FIRMID_FIELD.full_name = '.qlua.rpc.getDepoEx.Request.firmid'
module.REQUEST_FIRMID_FIELD.number = 1
module.REQUEST_FIRMID_FIELD.index = 0
module.REQUEST_FIRMID_FIELD.label = 1
module.REQUEST_FIRMID_FIELD.has_default_value = false
module.REQUEST_FIRMID_FIELD.default_value = ''
module.REQUEST_FIRMID_FIELD.type = 9
module.REQUEST_FIRMID_FIELD.cpp_type = 9

module.REQUEST_CLIENT_CODE_FIELD.name = 'client_code'
module.REQUEST_CLIENT_CODE_FIELD.full_name = '.qlua.rpc.getDepoEx.Request.client_code'
module.REQUEST_CLIENT_CODE_FIELD.number = 2
module.REQUEST_CLIENT_CODE_FIELD.index = 1
module.REQUEST_CLIENT_CODE_FIELD.label = 1
module.REQUEST_CLIENT_CODE_FIELD.has_default_value = false
module.REQUEST_CLIENT_CODE_FIELD.default_value = ''
module.REQUEST_CLIENT_CODE_FIELD.type = 9
module.REQUEST_CLIENT_CODE_FIELD.cpp_type = 9

module.REQUEST_SEC_CODE_FIELD.name = 'sec_code'
module.REQUEST_SEC_CODE_FIELD.full_name = '.qlua.rpc.getDepoEx.Request.sec_code'
module.REQUEST_SEC_CODE_FIELD.number = 3
module.REQUEST_SEC_CODE_FIELD.index = 2
module.REQUEST_SEC_CODE_FIELD.label = 1
module.REQUEST_SEC_CODE_FIELD.has_default_value = false
module.REQUEST_SEC_CODE_FIELD.default_value = ''
module.REQUEST_SEC_CODE_FIELD.type = 9
module.REQUEST_SEC_CODE_FIELD.cpp_type = 9

module.REQUEST_TRDACCID_FIELD.name = 'trdaccid'
module.REQUEST_TRDACCID_FIELD.full_name = '.qlua.rpc.getDepoEx.Request.trdaccid'
module.REQUEST_TRDACCID_FIELD.number = 4
module.REQUEST_TRDACCID_FIELD.index = 3
module.REQUEST_TRDACCID_FIELD.label = 1
module.REQUEST_TRDACCID_FIELD.has_default_value = false
module.REQUEST_TRDACCID_FIELD.default_value = ''
module.REQUEST_TRDACCID_FIELD.type = 9
module.REQUEST_TRDACCID_FIELD.cpp_type = 9

module.REQUEST_LIMIT_KIND_FIELD.name = 'limit_kind'
module.REQUEST_LIMIT_KIND_FIELD.full_name = '.qlua.rpc.getDepoEx.Request.limit_kind'
module.REQUEST_LIMIT_KIND_FIELD.number = 5
module.REQUEST_LIMIT_KIND_FIELD.index = 4
module.REQUEST_LIMIT_KIND_FIELD.label = 1
module.REQUEST_LIMIT_KIND_FIELD.has_default_value = false
module.REQUEST_LIMIT_KIND_FIELD.default_value = 0
module.REQUEST_LIMIT_KIND_FIELD.type = 5
module.REQUEST_LIMIT_KIND_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getDepoEx.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_FIRMID_FIELD, module.REQUEST_CLIENT_CODE_FIELD, module.REQUEST_SEC_CODE_FIELD, module.REQUEST_TRDACCID_FIELD, module.REQUEST_LIMIT_KIND_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_DEPO_EX_FIELD.name = 'depo_ex'
module.RESULT_DEPO_EX_FIELD.full_name = '.qlua.rpc.getDepoEx.Result.depo_ex'
module.RESULT_DEPO_EX_FIELD.number = 1
module.RESULT_DEPO_EX_FIELD.index = 0
module.RESULT_DEPO_EX_FIELD.label = 1
module.RESULT_DEPO_EX_FIELD.has_default_value = false
module.RESULT_DEPO_EX_FIELD.default_value = nil
module.RESULT_DEPO_EX_FIELD.message_type = imports['qlua/rpc/qlua_structures_pb'].DEPOLIMIT
module.RESULT_DEPO_EX_FIELD.type = 11
module.RESULT_DEPO_EX_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getDepoEx.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_DEPO_EX_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
