-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.REQUEST = protobuf.Descriptor()
module.REQUEST_PARAM_NAME_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_INFO_PARAM_FIELD = protobuf.FieldDescriptor()

module.REQUEST_PARAM_NAME_FIELD.name = 'param_name'
module.REQUEST_PARAM_NAME_FIELD.full_name = '.qlua.rpc.getInfoParam.Request.param_name'
module.REQUEST_PARAM_NAME_FIELD.number = 1
module.REQUEST_PARAM_NAME_FIELD.index = 0
module.REQUEST_PARAM_NAME_FIELD.label = 1
module.REQUEST_PARAM_NAME_FIELD.has_default_value = false
module.REQUEST_PARAM_NAME_FIELD.default_value = ''
module.REQUEST_PARAM_NAME_FIELD.type = 9
module.REQUEST_PARAM_NAME_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getInfoParam.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_PARAM_NAME_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_INFO_PARAM_FIELD.name = 'info_param'
module.RESULT_INFO_PARAM_FIELD.full_name = '.qlua.rpc.getInfoParam.Result.info_param'
module.RESULT_INFO_PARAM_FIELD.number = 1
module.RESULT_INFO_PARAM_FIELD.index = 0
module.RESULT_INFO_PARAM_FIELD.label = 1
module.RESULT_INFO_PARAM_FIELD.has_default_value = false
module.RESULT_INFO_PARAM_FIELD.default_value = ''
module.RESULT_INFO_PARAM_FIELD.type = 9
module.RESULT_INFO_PARAM_FIELD.cpp_type = 9

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getInfoParam.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_INFO_PARAM_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
