-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

local imports = {}
imports['qlua/rpc/getPortfolioInfo_pb'] = require 'qlua/rpc/getPortfolioInfo_pb'

module.PORTFOLIOINFOEX = protobuf.Descriptor()
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD = protobuf.FieldDescriptor()
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD = protobuf.FieldDescriptor()
module.REQUEST = protobuf.Descriptor()
module.REQUEST_FIRM_ID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CLIENT_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_LIMIT_KIND_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_PORTFOLIO_INFO_EX_FIELD = protobuf.FieldDescriptor()

module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.name = 'portfolio_info'
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.portfolio_info'
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.number = 1
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.index = 0
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.label = 1
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.default_value = nil
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.message_type = imports['qlua/rpc/getPortfolioInfo_pb'].PORTFOLIOINFO
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.type = 11
module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD.cpp_type = 10

module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.name = 'init_margin'
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.init_margin'
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.number = 2
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.index = 1
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.label = 1
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.default_value = ''
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.type = 9
module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.name = 'min_margin'
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.min_margin'
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.number = 3
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.index = 2
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.label = 1
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.default_value = ''
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.type = 9
module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.name = 'corrected_margin'
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.corrected_margin'
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.number = 4
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.index = 3
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.label = 1
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.default_value = ''
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.type = 9
module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.name = 'client_type'
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.client_type'
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.number = 5
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.index = 4
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.label = 1
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.default_value = ''
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.type = 9
module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.name = 'portfolio_value'
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.portfolio_value'
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.number = 6
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.index = 5
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.label = 1
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.default_value = ''
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.type = 9
module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.name = 'start_limit_open_pos'
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.start_limit_open_pos'
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.number = 7
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.index = 6
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.label = 1
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.default_value = ''
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.type = 9
module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.name = 'total_limit_open_pos'
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.total_limit_open_pos'
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.number = 8
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.index = 7
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.label = 1
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.default_value = ''
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.type = 9
module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.name = 'limit_open_pos'
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.limit_open_pos'
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.number = 9
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.index = 8
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.label = 1
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.default_value = ''
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.type = 9
module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.name = 'used_lim_open_pos'
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.used_lim_open_pos'
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.number = 10
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.index = 9
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.label = 1
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.default_value = ''
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.type = 9
module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.name = 'acc_var_margin'
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.acc_var_margin'
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.number = 11
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.index = 10
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.label = 1
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.default_value = ''
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.type = 9
module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.name = 'cl_var_margin'
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.cl_var_margin'
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.number = 12
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.index = 11
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.label = 1
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.default_value = ''
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.type = 9
module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.name = 'opt_liquid_cost'
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.opt_liquid_cost'
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.number = 13
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.index = 12
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.label = 1
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.default_value = ''
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.type = 9
module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.name = 'fut_asset'
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_asset'
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.number = 14
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.index = 13
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_ASSET_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.name = 'fut_total_asset'
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_total_asset'
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.number = 15
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.index = 14
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.name = 'fut_debt'
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_debt'
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.number = 16
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.index = 15
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_DEBT_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.name = 'fut_rate_asset'
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_rate_asset'
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.number = 17
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.index = 16
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.name = 'fut_rate_asset_open'
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_rate_asset_open'
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.number = 18
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.index = 17
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.name = 'fut_rate_go'
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_rate_go'
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.number = 19
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.index = 18
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.name = 'planed_rate_go'
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.planed_rate_go'
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.number = 20
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.index = 19
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.label = 1
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.default_value = ''
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.type = 9
module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.name = 'cash_leverage'
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.cash_leverage'
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.number = 21
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.index = 20
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.label = 1
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.default_value = ''
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.type = 9
module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.name = 'fut_position_type'
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_position_type'
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.number = 22
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.index = 21
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.name = 'fut_accured_int'
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx.fut_accured_int'
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.number = 23
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.index = 22
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.label = 1
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.has_default_value = false
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.default_value = ''
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.type = 9
module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD.cpp_type = 9

module.PORTFOLIOINFOEX.name = 'PortfolioInfoEx'
module.PORTFOLIOINFOEX.full_name = '.qlua.rpc.getPortfolioInfoEx.PortfolioInfoEx'
module.PORTFOLIOINFOEX.nested_types = {}
module.PORTFOLIOINFOEX.enum_types = {}
module.PORTFOLIOINFOEX.fields = {module.PORTFOLIOINFOEX_PORTFOLIO_INFO_FIELD, module.PORTFOLIOINFOEX_INIT_MARGIN_FIELD, module.PORTFOLIOINFOEX_MIN_MARGIN_FIELD, module.PORTFOLIOINFOEX_CORRECTED_MARGIN_FIELD, module.PORTFOLIOINFOEX_CLIENT_TYPE_FIELD, module.PORTFOLIOINFOEX_PORTFOLIO_VALUE_FIELD, module.PORTFOLIOINFOEX_START_LIMIT_OPEN_POS_FIELD, module.PORTFOLIOINFOEX_TOTAL_LIMIT_OPEN_POS_FIELD, module.PORTFOLIOINFOEX_LIMIT_OPEN_POS_FIELD, module.PORTFOLIOINFOEX_USED_LIM_OPEN_POS_FIELD, module.PORTFOLIOINFOEX_ACC_VAR_MARGIN_FIELD, module.PORTFOLIOINFOEX_CL_VAR_MARGIN_FIELD, module.PORTFOLIOINFOEX_OPT_LIQUID_COST_FIELD, module.PORTFOLIOINFOEX_FUT_ASSET_FIELD, module.PORTFOLIOINFOEX_FUT_TOTAL_ASSET_FIELD, module.PORTFOLIOINFOEX_FUT_DEBT_FIELD, module.PORTFOLIOINFOEX_FUT_RATE_ASSET_FIELD, module.PORTFOLIOINFOEX_FUT_RATE_ASSET_OPEN_FIELD, module.PORTFOLIOINFOEX_FUT_RATE_GO_FIELD, module.PORTFOLIOINFOEX_PLANED_RATE_GO_FIELD, module.PORTFOLIOINFOEX_CASH_LEVERAGE_FIELD, module.PORTFOLIOINFOEX_FUT_POSITION_TYPE_FIELD, module.PORTFOLIOINFOEX_FUT_ACCURED_INT_FIELD}
module.PORTFOLIOINFOEX.is_extendable = false
module.PORTFOLIOINFOEX.extensions = {}
module.REQUEST_FIRM_ID_FIELD.name = 'firm_id'
module.REQUEST_FIRM_ID_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.Request.firm_id'
module.REQUEST_FIRM_ID_FIELD.number = 1
module.REQUEST_FIRM_ID_FIELD.index = 0
module.REQUEST_FIRM_ID_FIELD.label = 1
module.REQUEST_FIRM_ID_FIELD.has_default_value = false
module.REQUEST_FIRM_ID_FIELD.default_value = ''
module.REQUEST_FIRM_ID_FIELD.type = 9
module.REQUEST_FIRM_ID_FIELD.cpp_type = 9

module.REQUEST_CLIENT_CODE_FIELD.name = 'client_code'
module.REQUEST_CLIENT_CODE_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.Request.client_code'
module.REQUEST_CLIENT_CODE_FIELD.number = 2
module.REQUEST_CLIENT_CODE_FIELD.index = 1
module.REQUEST_CLIENT_CODE_FIELD.label = 1
module.REQUEST_CLIENT_CODE_FIELD.has_default_value = false
module.REQUEST_CLIENT_CODE_FIELD.default_value = ''
module.REQUEST_CLIENT_CODE_FIELD.type = 9
module.REQUEST_CLIENT_CODE_FIELD.cpp_type = 9

module.REQUEST_LIMIT_KIND_FIELD.name = 'limit_kind'
module.REQUEST_LIMIT_KIND_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.Request.limit_kind'
module.REQUEST_LIMIT_KIND_FIELD.number = 3
module.REQUEST_LIMIT_KIND_FIELD.index = 2
module.REQUEST_LIMIT_KIND_FIELD.label = 1
module.REQUEST_LIMIT_KIND_FIELD.has_default_value = false
module.REQUEST_LIMIT_KIND_FIELD.default_value = 0
module.REQUEST_LIMIT_KIND_FIELD.type = 5
module.REQUEST_LIMIT_KIND_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getPortfolioInfoEx.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_FIRM_ID_FIELD, module.REQUEST_CLIENT_CODE_FIELD, module.REQUEST_LIMIT_KIND_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_PORTFOLIO_INFO_EX_FIELD.name = 'portfolio_info_ex'
module.RESULT_PORTFOLIO_INFO_EX_FIELD.full_name = '.qlua.rpc.getPortfolioInfoEx.Result.portfolio_info_ex'
module.RESULT_PORTFOLIO_INFO_EX_FIELD.number = 1
module.RESULT_PORTFOLIO_INFO_EX_FIELD.index = 0
module.RESULT_PORTFOLIO_INFO_EX_FIELD.label = 1
module.RESULT_PORTFOLIO_INFO_EX_FIELD.has_default_value = false
module.RESULT_PORTFOLIO_INFO_EX_FIELD.default_value = nil
module.RESULT_PORTFOLIO_INFO_EX_FIELD.message_type = module.PORTFOLIOINFOEX
module.RESULT_PORTFOLIO_INFO_EX_FIELD.type = 11
module.RESULT_PORTFOLIO_INFO_EX_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getPortfolioInfoEx.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_PORTFOLIO_INFO_EX_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.PortfolioInfoEx = protobuf.Message(module.PORTFOLIOINFOEX)
module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'PortfolioInfoEx','Request','Result'}
module.ENUM_TYPES = {}

return module
