-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.TRADEDATE = protobuf.Descriptor()
module.TRADEDATE_DATE_FIELD = protobuf.FieldDescriptor()
module.TRADEDATE_YEAR_FIELD = protobuf.FieldDescriptor()
module.TRADEDATE_MONTH_FIELD = protobuf.FieldDescriptor()
module.TRADEDATE_DAY_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_TRADE_DATE_FIELD = protobuf.FieldDescriptor()

module.TRADEDATE_DATE_FIELD.name = 'date'
module.TRADEDATE_DATE_FIELD.full_name = '.qlua.rpc.getTradeDate.TradeDate.date'
module.TRADEDATE_DATE_FIELD.number = 1
module.TRADEDATE_DATE_FIELD.index = 0
module.TRADEDATE_DATE_FIELD.label = 1
module.TRADEDATE_DATE_FIELD.has_default_value = false
module.TRADEDATE_DATE_FIELD.default_value = ''
module.TRADEDATE_DATE_FIELD.type = 9
module.TRADEDATE_DATE_FIELD.cpp_type = 9

module.TRADEDATE_YEAR_FIELD.name = 'year'
module.TRADEDATE_YEAR_FIELD.full_name = '.qlua.rpc.getTradeDate.TradeDate.year'
module.TRADEDATE_YEAR_FIELD.number = 2
module.TRADEDATE_YEAR_FIELD.index = 1
module.TRADEDATE_YEAR_FIELD.label = 1
module.TRADEDATE_YEAR_FIELD.has_default_value = false
module.TRADEDATE_YEAR_FIELD.default_value = 0
module.TRADEDATE_YEAR_FIELD.type = 13
module.TRADEDATE_YEAR_FIELD.cpp_type = 3

module.TRADEDATE_MONTH_FIELD.name = 'month'
module.TRADEDATE_MONTH_FIELD.full_name = '.qlua.rpc.getTradeDate.TradeDate.month'
module.TRADEDATE_MONTH_FIELD.number = 3
module.TRADEDATE_MONTH_FIELD.index = 2
module.TRADEDATE_MONTH_FIELD.label = 1
module.TRADEDATE_MONTH_FIELD.has_default_value = false
module.TRADEDATE_MONTH_FIELD.default_value = 0
module.TRADEDATE_MONTH_FIELD.type = 13
module.TRADEDATE_MONTH_FIELD.cpp_type = 3

module.TRADEDATE_DAY_FIELD.name = 'day'
module.TRADEDATE_DAY_FIELD.full_name = '.qlua.rpc.getTradeDate.TradeDate.day'
module.TRADEDATE_DAY_FIELD.number = 4
module.TRADEDATE_DAY_FIELD.index = 3
module.TRADEDATE_DAY_FIELD.label = 1
module.TRADEDATE_DAY_FIELD.has_default_value = false
module.TRADEDATE_DAY_FIELD.default_value = 0
module.TRADEDATE_DAY_FIELD.type = 13
module.TRADEDATE_DAY_FIELD.cpp_type = 3

module.TRADEDATE.name = 'TradeDate'
module.TRADEDATE.full_name = '.qlua.rpc.getTradeDate.TradeDate'
module.TRADEDATE.nested_types = {}
module.TRADEDATE.enum_types = {}
module.TRADEDATE.fields = {module.TRADEDATE_DATE_FIELD, module.TRADEDATE_YEAR_FIELD, module.TRADEDATE_MONTH_FIELD, module.TRADEDATE_DAY_FIELD}
module.TRADEDATE.is_extendable = false
module.TRADEDATE.extensions = {}
module.RESULT_TRADE_DATE_FIELD.name = 'trade_date'
module.RESULT_TRADE_DATE_FIELD.full_name = '.qlua.rpc.getTradeDate.Result.trade_date'
module.RESULT_TRADE_DATE_FIELD.number = 1
module.RESULT_TRADE_DATE_FIELD.index = 0
module.RESULT_TRADE_DATE_FIELD.label = 1
module.RESULT_TRADE_DATE_FIELD.has_default_value = false
module.RESULT_TRADE_DATE_FIELD.default_value = nil
module.RESULT_TRADE_DATE_FIELD.message_type = module.TRADEDATE
module.RESULT_TRADE_DATE_FIELD.type = 11
module.RESULT_TRADE_DATE_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getTradeDate.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_TRADE_DATE_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Result = protobuf.Message(module.RESULT)
module.TradeDate = protobuf.Message(module.TRADEDATE)


module.MESSAGE_TYPES = {'TradeDate','Result'}
module.ENUM_TYPES = {}

return module
