-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.REQUEST = protobuf.Descriptor()
module.REQUEST_T_ID_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_TOP_FIELD = protobuf.FieldDescriptor()
module.RESULT_LEFT_FIELD = protobuf.FieldDescriptor()
module.RESULT_BOTTOM_FIELD = protobuf.FieldDescriptor()
module.RESULT_RIGHT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_T_ID_FIELD.name = 't_id'
module.REQUEST_T_ID_FIELD.full_name = '.qlua.rpc.GetWindowRect.Request.t_id'
module.REQUEST_T_ID_FIELD.number = 1
module.REQUEST_T_ID_FIELD.index = 0
module.REQUEST_T_ID_FIELD.label = 1
module.REQUEST_T_ID_FIELD.has_default_value = false
module.REQUEST_T_ID_FIELD.default_value = 0
module.REQUEST_T_ID_FIELD.type = 5
module.REQUEST_T_ID_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.GetWindowRect.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_T_ID_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_TOP_FIELD.name = 'top'
module.RESULT_TOP_FIELD.full_name = '.qlua.rpc.GetWindowRect.Result.top'
module.RESULT_TOP_FIELD.number = 1
module.RESULT_TOP_FIELD.index = 0
module.RESULT_TOP_FIELD.label = 1
module.RESULT_TOP_FIELD.has_default_value = false
module.RESULT_TOP_FIELD.default_value = 0
module.RESULT_TOP_FIELD.type = 5
module.RESULT_TOP_FIELD.cpp_type = 1

module.RESULT_LEFT_FIELD.name = 'left'
module.RESULT_LEFT_FIELD.full_name = '.qlua.rpc.GetWindowRect.Result.left'
module.RESULT_LEFT_FIELD.number = 2
module.RESULT_LEFT_FIELD.index = 1
module.RESULT_LEFT_FIELD.label = 1
module.RESULT_LEFT_FIELD.has_default_value = false
module.RESULT_LEFT_FIELD.default_value = 0
module.RESULT_LEFT_FIELD.type = 5
module.RESULT_LEFT_FIELD.cpp_type = 1

module.RESULT_BOTTOM_FIELD.name = 'bottom'
module.RESULT_BOTTOM_FIELD.full_name = '.qlua.rpc.GetWindowRect.Result.bottom'
module.RESULT_BOTTOM_FIELD.number = 3
module.RESULT_BOTTOM_FIELD.index = 2
module.RESULT_BOTTOM_FIELD.label = 1
module.RESULT_BOTTOM_FIELD.has_default_value = false
module.RESULT_BOTTOM_FIELD.default_value = 0
module.RESULT_BOTTOM_FIELD.type = 5
module.RESULT_BOTTOM_FIELD.cpp_type = 1

module.RESULT_RIGHT_FIELD.name = 'right'
module.RESULT_RIGHT_FIELD.full_name = '.qlua.rpc.GetWindowRect.Result.right'
module.RESULT_RIGHT_FIELD.number = 4
module.RESULT_RIGHT_FIELD.index = 3
module.RESULT_RIGHT_FIELD.label = 1
module.RESULT_RIGHT_FIELD.has_default_value = false
module.RESULT_RIGHT_FIELD.default_value = 0
module.RESULT_RIGHT_FIELD.type = 5
module.RESULT_RIGHT_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.GetWindowRect.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_TOP_FIELD, module.RESULT_LEFT_FIELD, module.RESULT_BOTTOM_FIELD, module.RESULT_RIGHT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
