-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.TABLEENTRY = protobuf.Descriptor()
module.TABLEENTRY_K_FIELD = protobuf.FieldDescriptor()
module.TABLEENTRY_V_FIELD = protobuf.FieldDescriptor()

module.TABLEENTRY_K_FIELD.name = 'k'
module.TABLEENTRY_K_FIELD.full_name = '.qlua.types.TableEntry.k'
module.TABLEENTRY_K_FIELD.number = 1
module.TABLEENTRY_K_FIELD.index = 0
module.TABLEENTRY_K_FIELD.label = 1
module.TABLEENTRY_K_FIELD.has_default_value = false
module.TABLEENTRY_K_FIELD.default_value = ''
module.TABLEENTRY_K_FIELD.type = 9
module.TABLEENTRY_K_FIELD.cpp_type = 9

module.TABLEENTRY_V_FIELD.name = 'v'
module.TABLEENTRY_V_FIELD.full_name = '.qlua.types.TableEntry.v'
module.TABLEENTRY_V_FIELD.number = 2
module.TABLEENTRY_V_FIELD.index = 1
module.TABLEENTRY_V_FIELD.label = 1
module.TABLEENTRY_V_FIELD.has_default_value = false
module.TABLEENTRY_V_FIELD.default_value = ''
module.TABLEENTRY_V_FIELD.type = 9
module.TABLEENTRY_V_FIELD.cpp_type = 9

module.TABLEENTRY.name = 'TableEntry'
module.TABLEENTRY.full_name = '.qlua.types.TableEntry'
module.TABLEENTRY.nested_types = {}
module.TABLEENTRY.enum_types = {}
module.TABLEENTRY.fields = {module.TABLEENTRY_K_FIELD, module.TABLEENTRY_V_FIELD}
module.TABLEENTRY.is_extendable = false
module.TABLEENTRY.extensions = {}

module.TableEntry = protobuf.Message(module.TABLEENTRY)


module.MESSAGE_TYPES = {'TableEntry'}
module.ENUM_TYPES = {}

return module
