-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'


module.REQUEST = protobuf.Descriptor()
module.REQUEST_TABLE_ID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_ROW_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_TABLE_ID_FIELD.name = 'table_id'
module.REQUEST_TABLE_ID_FIELD.full_name = '.qlua.rpc.SetSelectedRow.Request.table_id'
module.REQUEST_TABLE_ID_FIELD.number = 1
module.REQUEST_TABLE_ID_FIELD.index = 0
module.REQUEST_TABLE_ID_FIELD.label = 1
module.REQUEST_TABLE_ID_FIELD.has_default_value = false
module.REQUEST_TABLE_ID_FIELD.default_value = 0
module.REQUEST_TABLE_ID_FIELD.type = 5
module.REQUEST_TABLE_ID_FIELD.cpp_type = 1

module.REQUEST_ROW_FIELD.name = 'row'
module.REQUEST_ROW_FIELD.full_name = '.qlua.rpc.SetSelectedRow.Request.row'
module.REQUEST_ROW_FIELD.number = 2
module.REQUEST_ROW_FIELD.index = 1
module.REQUEST_ROW_FIELD.label = 1
module.REQUEST_ROW_FIELD.has_default_value = false
module.REQUEST_ROW_FIELD.default_value = 0
module.REQUEST_ROW_FIELD.type = 13
module.REQUEST_ROW_FIELD.cpp_type = 3

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.SetSelectedRow.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_TABLE_ID_FIELD, module.REQUEST_ROW_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.SetSelectedRow.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = 0
module.RESULT_RESULT_FIELD.type = 5
module.RESULT_RESULT_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.SetSelectedRow.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
