-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_CLASS_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_SEC_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CLIENT_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_ACCOUNT_FIELD = protobuf.FieldDescriptor()
module.REQUEST_PRICE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_IS_BUY_FIELD = protobuf.FieldDescriptor()
module.REQUEST_IS_MARKET_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_QTY_FIELD = protobuf.FieldDescriptor()
module.RESULT_COMISSION_FIELD = protobuf.FieldDescriptor()

module.REQUEST_CLASS_CODE_FIELD.name = 'class_code'
module.REQUEST_CLASS_CODE_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.class_code'
module.REQUEST_CLASS_CODE_FIELD.number = 1
module.REQUEST_CLASS_CODE_FIELD.index = 0
module.REQUEST_CLASS_CODE_FIELD.label = 1
module.REQUEST_CLASS_CODE_FIELD.has_default_value = false
module.REQUEST_CLASS_CODE_FIELD.default_value = ''
module.REQUEST_CLASS_CODE_FIELD.type = 9
module.REQUEST_CLASS_CODE_FIELD.cpp_type = 9

module.REQUEST_SEC_CODE_FIELD.name = 'sec_code'
module.REQUEST_SEC_CODE_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.sec_code'
module.REQUEST_SEC_CODE_FIELD.number = 2
module.REQUEST_SEC_CODE_FIELD.index = 1
module.REQUEST_SEC_CODE_FIELD.label = 1
module.REQUEST_SEC_CODE_FIELD.has_default_value = false
module.REQUEST_SEC_CODE_FIELD.default_value = ''
module.REQUEST_SEC_CODE_FIELD.type = 9
module.REQUEST_SEC_CODE_FIELD.cpp_type = 9

module.REQUEST_CLIENT_CODE_FIELD.name = 'client_code'
module.REQUEST_CLIENT_CODE_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.client_code'
module.REQUEST_CLIENT_CODE_FIELD.number = 3
module.REQUEST_CLIENT_CODE_FIELD.index = 2
module.REQUEST_CLIENT_CODE_FIELD.label = 1
module.REQUEST_CLIENT_CODE_FIELD.has_default_value = false
module.REQUEST_CLIENT_CODE_FIELD.default_value = ''
module.REQUEST_CLIENT_CODE_FIELD.type = 9
module.REQUEST_CLIENT_CODE_FIELD.cpp_type = 9

module.REQUEST_ACCOUNT_FIELD.name = 'account'
module.REQUEST_ACCOUNT_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.account'
module.REQUEST_ACCOUNT_FIELD.number = 4
module.REQUEST_ACCOUNT_FIELD.index = 3
module.REQUEST_ACCOUNT_FIELD.label = 1
module.REQUEST_ACCOUNT_FIELD.has_default_value = false
module.REQUEST_ACCOUNT_FIELD.default_value = ''
module.REQUEST_ACCOUNT_FIELD.type = 9
module.REQUEST_ACCOUNT_FIELD.cpp_type = 9

module.REQUEST_PRICE_FIELD.name = 'price'
module.REQUEST_PRICE_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.price'
module.REQUEST_PRICE_FIELD.number = 5
module.REQUEST_PRICE_FIELD.index = 4
module.REQUEST_PRICE_FIELD.label = 1
module.REQUEST_PRICE_FIELD.has_default_value = false
module.REQUEST_PRICE_FIELD.default_value = ''
module.REQUEST_PRICE_FIELD.type = 9
module.REQUEST_PRICE_FIELD.cpp_type = 9

module.REQUEST_IS_BUY_FIELD.name = 'is_buy'
module.REQUEST_IS_BUY_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.is_buy'
module.REQUEST_IS_BUY_FIELD.number = 6
module.REQUEST_IS_BUY_FIELD.index = 5
module.REQUEST_IS_BUY_FIELD.label = 1
module.REQUEST_IS_BUY_FIELD.has_default_value = false
module.REQUEST_IS_BUY_FIELD.default_value = false
module.REQUEST_IS_BUY_FIELD.type = 8
module.REQUEST_IS_BUY_FIELD.cpp_type = 7

module.REQUEST_IS_MARKET_FIELD.name = 'is_market'
module.REQUEST_IS_MARKET_FIELD.full_name = '.qlua.rpc.CalcBuySell.Request.is_market'
module.REQUEST_IS_MARKET_FIELD.number = 7
module.REQUEST_IS_MARKET_FIELD.index = 6
module.REQUEST_IS_MARKET_FIELD.label = 1
module.REQUEST_IS_MARKET_FIELD.has_default_value = false
module.REQUEST_IS_MARKET_FIELD.default_value = false
module.REQUEST_IS_MARKET_FIELD.type = 8
module.REQUEST_IS_MARKET_FIELD.cpp_type = 7

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.CalcBuySell.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CLASS_CODE_FIELD, module.REQUEST_SEC_CODE_FIELD, module.REQUEST_CLIENT_CODE_FIELD, module.REQUEST_ACCOUNT_FIELD, module.REQUEST_PRICE_FIELD, module.REQUEST_IS_BUY_FIELD, module.REQUEST_IS_MARKET_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_QTY_FIELD.name = 'qty'
module.RESULT_QTY_FIELD.full_name = '.qlua.rpc.CalcBuySell.Result.qty'
module.RESULT_QTY_FIELD.number = 1
module.RESULT_QTY_FIELD.index = 0
module.RESULT_QTY_FIELD.label = 1
module.RESULT_QTY_FIELD.has_default_value = false
module.RESULT_QTY_FIELD.default_value = 0
module.RESULT_QTY_FIELD.type = 5
module.RESULT_QTY_FIELD.cpp_type = 1

module.RESULT_COMISSION_FIELD.name = 'comission'
module.RESULT_COMISSION_FIELD.full_name = '.qlua.rpc.CalcBuySell.Result.comission'
module.RESULT_COMISSION_FIELD.number = 2
module.RESULT_COMISSION_FIELD.index = 1
module.RESULT_COMISSION_FIELD.label = 1
module.RESULT_COMISSION_FIELD.has_default_value = false
module.RESULT_COMISSION_FIELD.default_value = ''
module.RESULT_COMISSION_FIELD.type = 9
module.RESULT_COMISSION_FIELD.cpp_type = 9

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.CalcBuySell.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_QTY_FIELD, module.RESULT_COMISSION_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
