-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_CLASS_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_SEC_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_DB_NAME_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_CLASS_CODE_FIELD.name = 'class_code'
module.REQUEST_CLASS_CODE_FIELD.full_name = '.qlua.rpc.CancelParamRequest.Request.class_code'
module.REQUEST_CLASS_CODE_FIELD.number = 1
module.REQUEST_CLASS_CODE_FIELD.index = 0
module.REQUEST_CLASS_CODE_FIELD.label = 1
module.REQUEST_CLASS_CODE_FIELD.has_default_value = false
module.REQUEST_CLASS_CODE_FIELD.default_value = ''
module.REQUEST_CLASS_CODE_FIELD.type = 9
module.REQUEST_CLASS_CODE_FIELD.cpp_type = 9

module.REQUEST_SEC_CODE_FIELD.name = 'sec_code'
module.REQUEST_SEC_CODE_FIELD.full_name = '.qlua.rpc.CancelParamRequest.Request.sec_code'
module.REQUEST_SEC_CODE_FIELD.number = 2
module.REQUEST_SEC_CODE_FIELD.index = 1
module.REQUEST_SEC_CODE_FIELD.label = 1
module.REQUEST_SEC_CODE_FIELD.has_default_value = false
module.REQUEST_SEC_CODE_FIELD.default_value = ''
module.REQUEST_SEC_CODE_FIELD.type = 9
module.REQUEST_SEC_CODE_FIELD.cpp_type = 9

module.REQUEST_DB_NAME_FIELD.name = 'db_name'
module.REQUEST_DB_NAME_FIELD.full_name = '.qlua.rpc.CancelParamRequest.Request.db_name'
module.REQUEST_DB_NAME_FIELD.number = 3
module.REQUEST_DB_NAME_FIELD.index = 2
module.REQUEST_DB_NAME_FIELD.label = 1
module.REQUEST_DB_NAME_FIELD.has_default_value = false
module.REQUEST_DB_NAME_FIELD.default_value = ''
module.REQUEST_DB_NAME_FIELD.type = 9
module.REQUEST_DB_NAME_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.CancelParamRequest.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CLASS_CODE_FIELD, module.REQUEST_SEC_CODE_FIELD, module.REQUEST_DB_NAME_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.CancelParamRequest.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = false
module.RESULT_RESULT_FIELD.type = 8
module.RESULT_RESULT_FIELD.cpp_type = 7

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.CancelParamRequest.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
