-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.BUYSELLINFO = protobuf.Descriptor()
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_IS_ASSET_SEC_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_BALANCE_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_CAN_BUY_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_CAN_SELL_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_POSITION_VALUATION_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_VALUE_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_OPEN_VALUE_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_LIM_LONG_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_LONG_COEF_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_LIM_SHORT_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_SHORT_COEF_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_VALUE_COEF_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_SHARE_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_LONG_WA_PRICE_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_PROFIT_LOSS_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_SPREAD_HC_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_CAN_BUY_OWN_FIELD = protobuf.FieldDescriptor()
module.BUYSELLINFO_CAN_SELL_OWN_FIELD = protobuf.FieldDescriptor()
module.REQUEST = protobuf.Descriptor()
module.REQUEST_FIRM_ID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CLIENT_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CLASS_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_SEC_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_PRICE_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_BUY_SELL_INFO_FIELD = protobuf.FieldDescriptor()

module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.name = 'is_margin_sec'
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.is_margin_sec'
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.number = 1
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.index = 0
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.label = 1
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.has_default_value = false
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.default_value = ''
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.type = 9
module.BUYSELLINFO_IS_MARGIN_SEC_FIELD.cpp_type = 9

module.BUYSELLINFO_IS_ASSET_SEC_FIELD.name = 'is_asset_sec'
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.is_asset_sec'
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.number = 2
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.index = 1
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.label = 1
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.has_default_value = false
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.default_value = ''
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.type = 9
module.BUYSELLINFO_IS_ASSET_SEC_FIELD.cpp_type = 9

module.BUYSELLINFO_BALANCE_FIELD.name = 'balance'
module.BUYSELLINFO_BALANCE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.balance'
module.BUYSELLINFO_BALANCE_FIELD.number = 3
module.BUYSELLINFO_BALANCE_FIELD.index = 2
module.BUYSELLINFO_BALANCE_FIELD.label = 1
module.BUYSELLINFO_BALANCE_FIELD.has_default_value = false
module.BUYSELLINFO_BALANCE_FIELD.default_value = ''
module.BUYSELLINFO_BALANCE_FIELD.type = 9
module.BUYSELLINFO_BALANCE_FIELD.cpp_type = 9

module.BUYSELLINFO_CAN_BUY_FIELD.name = 'can_buy'
module.BUYSELLINFO_CAN_BUY_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.can_buy'
module.BUYSELLINFO_CAN_BUY_FIELD.number = 4
module.BUYSELLINFO_CAN_BUY_FIELD.index = 3
module.BUYSELLINFO_CAN_BUY_FIELD.label = 1
module.BUYSELLINFO_CAN_BUY_FIELD.has_default_value = false
module.BUYSELLINFO_CAN_BUY_FIELD.default_value = ''
module.BUYSELLINFO_CAN_BUY_FIELD.type = 9
module.BUYSELLINFO_CAN_BUY_FIELD.cpp_type = 9

module.BUYSELLINFO_CAN_SELL_FIELD.name = 'can_sell'
module.BUYSELLINFO_CAN_SELL_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.can_sell'
module.BUYSELLINFO_CAN_SELL_FIELD.number = 5
module.BUYSELLINFO_CAN_SELL_FIELD.index = 4
module.BUYSELLINFO_CAN_SELL_FIELD.label = 1
module.BUYSELLINFO_CAN_SELL_FIELD.has_default_value = false
module.BUYSELLINFO_CAN_SELL_FIELD.default_value = ''
module.BUYSELLINFO_CAN_SELL_FIELD.type = 9
module.BUYSELLINFO_CAN_SELL_FIELD.cpp_type = 9

module.BUYSELLINFO_POSITION_VALUATION_FIELD.name = 'position_valuation'
module.BUYSELLINFO_POSITION_VALUATION_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.position_valuation'
module.BUYSELLINFO_POSITION_VALUATION_FIELD.number = 6
module.BUYSELLINFO_POSITION_VALUATION_FIELD.index = 5
module.BUYSELLINFO_POSITION_VALUATION_FIELD.label = 1
module.BUYSELLINFO_POSITION_VALUATION_FIELD.has_default_value = false
module.BUYSELLINFO_POSITION_VALUATION_FIELD.default_value = ''
module.BUYSELLINFO_POSITION_VALUATION_FIELD.type = 9
module.BUYSELLINFO_POSITION_VALUATION_FIELD.cpp_type = 9

module.BUYSELLINFO_VALUE_FIELD.name = 'value'
module.BUYSELLINFO_VALUE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.value'
module.BUYSELLINFO_VALUE_FIELD.number = 7
module.BUYSELLINFO_VALUE_FIELD.index = 6
module.BUYSELLINFO_VALUE_FIELD.label = 1
module.BUYSELLINFO_VALUE_FIELD.has_default_value = false
module.BUYSELLINFO_VALUE_FIELD.default_value = ''
module.BUYSELLINFO_VALUE_FIELD.type = 9
module.BUYSELLINFO_VALUE_FIELD.cpp_type = 9

module.BUYSELLINFO_OPEN_VALUE_FIELD.name = 'open_value'
module.BUYSELLINFO_OPEN_VALUE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.open_value'
module.BUYSELLINFO_OPEN_VALUE_FIELD.number = 8
module.BUYSELLINFO_OPEN_VALUE_FIELD.index = 7
module.BUYSELLINFO_OPEN_VALUE_FIELD.label = 1
module.BUYSELLINFO_OPEN_VALUE_FIELD.has_default_value = false
module.BUYSELLINFO_OPEN_VALUE_FIELD.default_value = ''
module.BUYSELLINFO_OPEN_VALUE_FIELD.type = 9
module.BUYSELLINFO_OPEN_VALUE_FIELD.cpp_type = 9

module.BUYSELLINFO_LIM_LONG_FIELD.name = 'lim_long'
module.BUYSELLINFO_LIM_LONG_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.lim_long'
module.BUYSELLINFO_LIM_LONG_FIELD.number = 9
module.BUYSELLINFO_LIM_LONG_FIELD.index = 8
module.BUYSELLINFO_LIM_LONG_FIELD.label = 1
module.BUYSELLINFO_LIM_LONG_FIELD.has_default_value = false
module.BUYSELLINFO_LIM_LONG_FIELD.default_value = ''
module.BUYSELLINFO_LIM_LONG_FIELD.type = 9
module.BUYSELLINFO_LIM_LONG_FIELD.cpp_type = 9

module.BUYSELLINFO_LONG_COEF_FIELD.name = 'long_coef'
module.BUYSELLINFO_LONG_COEF_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.long_coef'
module.BUYSELLINFO_LONG_COEF_FIELD.number = 10
module.BUYSELLINFO_LONG_COEF_FIELD.index = 9
module.BUYSELLINFO_LONG_COEF_FIELD.label = 1
module.BUYSELLINFO_LONG_COEF_FIELD.has_default_value = false
module.BUYSELLINFO_LONG_COEF_FIELD.default_value = ''
module.BUYSELLINFO_LONG_COEF_FIELD.type = 9
module.BUYSELLINFO_LONG_COEF_FIELD.cpp_type = 9

module.BUYSELLINFO_LIM_SHORT_FIELD.name = 'lim_short'
module.BUYSELLINFO_LIM_SHORT_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.lim_short'
module.BUYSELLINFO_LIM_SHORT_FIELD.number = 11
module.BUYSELLINFO_LIM_SHORT_FIELD.index = 10
module.BUYSELLINFO_LIM_SHORT_FIELD.label = 1
module.BUYSELLINFO_LIM_SHORT_FIELD.has_default_value = false
module.BUYSELLINFO_LIM_SHORT_FIELD.default_value = ''
module.BUYSELLINFO_LIM_SHORT_FIELD.type = 9
module.BUYSELLINFO_LIM_SHORT_FIELD.cpp_type = 9

module.BUYSELLINFO_SHORT_COEF_FIELD.name = 'short_coef'
module.BUYSELLINFO_SHORT_COEF_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.short_coef'
module.BUYSELLINFO_SHORT_COEF_FIELD.number = 12
module.BUYSELLINFO_SHORT_COEF_FIELD.index = 11
module.BUYSELLINFO_SHORT_COEF_FIELD.label = 1
module.BUYSELLINFO_SHORT_COEF_FIELD.has_default_value = false
module.BUYSELLINFO_SHORT_COEF_FIELD.default_value = ''
module.BUYSELLINFO_SHORT_COEF_FIELD.type = 9
module.BUYSELLINFO_SHORT_COEF_FIELD.cpp_type = 9

module.BUYSELLINFO_VALUE_COEF_FIELD.name = 'value_coef'
module.BUYSELLINFO_VALUE_COEF_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.value_coef'
module.BUYSELLINFO_VALUE_COEF_FIELD.number = 13
module.BUYSELLINFO_VALUE_COEF_FIELD.index = 12
module.BUYSELLINFO_VALUE_COEF_FIELD.label = 1
module.BUYSELLINFO_VALUE_COEF_FIELD.has_default_value = false
module.BUYSELLINFO_VALUE_COEF_FIELD.default_value = ''
module.BUYSELLINFO_VALUE_COEF_FIELD.type = 9
module.BUYSELLINFO_VALUE_COEF_FIELD.cpp_type = 9

module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.name = 'open_value_coef'
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.open_value_coef'
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.number = 14
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.index = 13
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.label = 1
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.has_default_value = false
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.default_value = ''
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.type = 9
module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD.cpp_type = 9

module.BUYSELLINFO_SHARE_FIELD.name = 'share'
module.BUYSELLINFO_SHARE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.share'
module.BUYSELLINFO_SHARE_FIELD.number = 15
module.BUYSELLINFO_SHARE_FIELD.index = 14
module.BUYSELLINFO_SHARE_FIELD.label = 1
module.BUYSELLINFO_SHARE_FIELD.has_default_value = false
module.BUYSELLINFO_SHARE_FIELD.default_value = ''
module.BUYSELLINFO_SHARE_FIELD.type = 9
module.BUYSELLINFO_SHARE_FIELD.cpp_type = 9

module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.name = 'short_wa_price'
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.short_wa_price'
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.number = 16
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.index = 15
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.label = 1
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.has_default_value = false
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.default_value = ''
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.type = 9
module.BUYSELLINFO_SHORT_WA_PRICE_FIELD.cpp_type = 9

module.BUYSELLINFO_LONG_WA_PRICE_FIELD.name = 'long_wa_price'
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.long_wa_price'
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.number = 17
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.index = 16
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.label = 1
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.has_default_value = false
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.default_value = ''
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.type = 9
module.BUYSELLINFO_LONG_WA_PRICE_FIELD.cpp_type = 9

module.BUYSELLINFO_PROFIT_LOSS_FIELD.name = 'profit_loss'
module.BUYSELLINFO_PROFIT_LOSS_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.profit_loss'
module.BUYSELLINFO_PROFIT_LOSS_FIELD.number = 18
module.BUYSELLINFO_PROFIT_LOSS_FIELD.index = 17
module.BUYSELLINFO_PROFIT_LOSS_FIELD.label = 1
module.BUYSELLINFO_PROFIT_LOSS_FIELD.has_default_value = false
module.BUYSELLINFO_PROFIT_LOSS_FIELD.default_value = ''
module.BUYSELLINFO_PROFIT_LOSS_FIELD.type = 9
module.BUYSELLINFO_PROFIT_LOSS_FIELD.cpp_type = 9

module.BUYSELLINFO_SPREAD_HC_FIELD.name = 'spread_hc'
module.BUYSELLINFO_SPREAD_HC_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.spread_hc'
module.BUYSELLINFO_SPREAD_HC_FIELD.number = 19
module.BUYSELLINFO_SPREAD_HC_FIELD.index = 18
module.BUYSELLINFO_SPREAD_HC_FIELD.label = 1
module.BUYSELLINFO_SPREAD_HC_FIELD.has_default_value = false
module.BUYSELLINFO_SPREAD_HC_FIELD.default_value = ''
module.BUYSELLINFO_SPREAD_HC_FIELD.type = 9
module.BUYSELLINFO_SPREAD_HC_FIELD.cpp_type = 9

module.BUYSELLINFO_CAN_BUY_OWN_FIELD.name = 'can_buy_own'
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.can_buy_own'
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.number = 20
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.index = 19
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.label = 1
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.has_default_value = false
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.default_value = ''
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.type = 9
module.BUYSELLINFO_CAN_BUY_OWN_FIELD.cpp_type = 9

module.BUYSELLINFO_CAN_SELL_OWN_FIELD.name = 'can_sell_own'
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo.can_sell_own'
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.number = 21
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.index = 20
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.label = 1
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.has_default_value = false
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.default_value = ''
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.type = 9
module.BUYSELLINFO_CAN_SELL_OWN_FIELD.cpp_type = 9

module.BUYSELLINFO.name = 'BuySellInfo'
module.BUYSELLINFO.full_name = '.qlua.rpc.getBuySellInfo.BuySellInfo'
module.BUYSELLINFO.nested_types = {}
module.BUYSELLINFO.enum_types = {}
module.BUYSELLINFO.fields = {module.BUYSELLINFO_IS_MARGIN_SEC_FIELD, module.BUYSELLINFO_IS_ASSET_SEC_FIELD, module.BUYSELLINFO_BALANCE_FIELD, module.BUYSELLINFO_CAN_BUY_FIELD, module.BUYSELLINFO_CAN_SELL_FIELD, module.BUYSELLINFO_POSITION_VALUATION_FIELD, module.BUYSELLINFO_VALUE_FIELD, module.BUYSELLINFO_OPEN_VALUE_FIELD, module.BUYSELLINFO_LIM_LONG_FIELD, module.BUYSELLINFO_LONG_COEF_FIELD, module.BUYSELLINFO_LIM_SHORT_FIELD, module.BUYSELLINFO_SHORT_COEF_FIELD, module.BUYSELLINFO_VALUE_COEF_FIELD, module.BUYSELLINFO_OPEN_VALUE_COEF_FIELD, module.BUYSELLINFO_SHARE_FIELD, module.BUYSELLINFO_SHORT_WA_PRICE_FIELD, module.BUYSELLINFO_LONG_WA_PRICE_FIELD, module.BUYSELLINFO_PROFIT_LOSS_FIELD, module.BUYSELLINFO_SPREAD_HC_FIELD, module.BUYSELLINFO_CAN_BUY_OWN_FIELD, module.BUYSELLINFO_CAN_SELL_OWN_FIELD}
module.BUYSELLINFO.is_extendable = false
module.BUYSELLINFO.extensions = {}
module.REQUEST_FIRM_ID_FIELD.name = 'firm_id'
module.REQUEST_FIRM_ID_FIELD.full_name = '.qlua.rpc.getBuySellInfo.Request.firm_id'
module.REQUEST_FIRM_ID_FIELD.number = 1
module.REQUEST_FIRM_ID_FIELD.index = 0
module.REQUEST_FIRM_ID_FIELD.label = 1
module.REQUEST_FIRM_ID_FIELD.has_default_value = false
module.REQUEST_FIRM_ID_FIELD.default_value = ''
module.REQUEST_FIRM_ID_FIELD.type = 9
module.REQUEST_FIRM_ID_FIELD.cpp_type = 9

module.REQUEST_CLIENT_CODE_FIELD.name = 'client_code'
module.REQUEST_CLIENT_CODE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.Request.client_code'
module.REQUEST_CLIENT_CODE_FIELD.number = 2
module.REQUEST_CLIENT_CODE_FIELD.index = 1
module.REQUEST_CLIENT_CODE_FIELD.label = 1
module.REQUEST_CLIENT_CODE_FIELD.has_default_value = false
module.REQUEST_CLIENT_CODE_FIELD.default_value = ''
module.REQUEST_CLIENT_CODE_FIELD.type = 9
module.REQUEST_CLIENT_CODE_FIELD.cpp_type = 9

module.REQUEST_CLASS_CODE_FIELD.name = 'class_code'
module.REQUEST_CLASS_CODE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.Request.class_code'
module.REQUEST_CLASS_CODE_FIELD.number = 3
module.REQUEST_CLASS_CODE_FIELD.index = 2
module.REQUEST_CLASS_CODE_FIELD.label = 1
module.REQUEST_CLASS_CODE_FIELD.has_default_value = false
module.REQUEST_CLASS_CODE_FIELD.default_value = ''
module.REQUEST_CLASS_CODE_FIELD.type = 9
module.REQUEST_CLASS_CODE_FIELD.cpp_type = 9

module.REQUEST_SEC_CODE_FIELD.name = 'sec_code'
module.REQUEST_SEC_CODE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.Request.sec_code'
module.REQUEST_SEC_CODE_FIELD.number = 4
module.REQUEST_SEC_CODE_FIELD.index = 3
module.REQUEST_SEC_CODE_FIELD.label = 1
module.REQUEST_SEC_CODE_FIELD.has_default_value = false
module.REQUEST_SEC_CODE_FIELD.default_value = ''
module.REQUEST_SEC_CODE_FIELD.type = 9
module.REQUEST_SEC_CODE_FIELD.cpp_type = 9

module.REQUEST_PRICE_FIELD.name = 'price'
module.REQUEST_PRICE_FIELD.full_name = '.qlua.rpc.getBuySellInfo.Request.price'
module.REQUEST_PRICE_FIELD.number = 5
module.REQUEST_PRICE_FIELD.index = 4
module.REQUEST_PRICE_FIELD.label = 1
module.REQUEST_PRICE_FIELD.has_default_value = false
module.REQUEST_PRICE_FIELD.default_value = ''
module.REQUEST_PRICE_FIELD.type = 9
module.REQUEST_PRICE_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getBuySellInfo.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_FIRM_ID_FIELD, module.REQUEST_CLIENT_CODE_FIELD, module.REQUEST_CLASS_CODE_FIELD, module.REQUEST_SEC_CODE_FIELD, module.REQUEST_PRICE_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_BUY_SELL_INFO_FIELD.name = 'buy_sell_info'
module.RESULT_BUY_SELL_INFO_FIELD.full_name = '.qlua.rpc.getBuySellInfo.Result.buy_sell_info'
module.RESULT_BUY_SELL_INFO_FIELD.number = 1
module.RESULT_BUY_SELL_INFO_FIELD.index = 0
module.RESULT_BUY_SELL_INFO_FIELD.label = 1
module.RESULT_BUY_SELL_INFO_FIELD.has_default_value = false
module.RESULT_BUY_SELL_INFO_FIELD.default_value = nil
module.RESULT_BUY_SELL_INFO_FIELD.message_type = module.BUYSELLINFO
module.RESULT_BUY_SELL_INFO_FIELD.type = 11
module.RESULT_BUY_SELL_INFO_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getBuySellInfo.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_BUY_SELL_INFO_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.BuySellInfo = protobuf.Message(module.BUYSELLINFO)
module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'BuySellInfo','Request','Result'}
module.ENUM_TYPES = {}

return module
