-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.DEPO = protobuf.Descriptor()
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_CURRENT_BALANCE_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_LIMIT_LOCKED_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_CURRENT_LIMIT_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_OPEN_BALANCE_FIELD = protobuf.FieldDescriptor()
module.DEPO_DEPO_OPEN_LIMIT_FIELD = protobuf.FieldDescriptor()
module.REQUEST = protobuf.Descriptor()
module.REQUEST_CLIENT_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_FIRMID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_SEC_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TRDACCID_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_DEPO_FIELD = protobuf.FieldDescriptor()

module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.name = 'depo_limit_locked_buy_value'
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_limit_locked_buy_value'
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.number = 1
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.index = 0
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.label = 1
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.has_default_value = false
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.default_value = ''
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.type = 9
module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD.cpp_type = 9

module.DEPO_DEPO_CURRENT_BALANCE_FIELD.name = 'depo_current_balance'
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_current_balance'
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.number = 2
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.index = 1
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.label = 1
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.has_default_value = false
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.default_value = ''
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.type = 9
module.DEPO_DEPO_CURRENT_BALANCE_FIELD.cpp_type = 9

module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.name = 'depo_limit_locked_buy'
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_limit_locked_buy'
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.number = 3
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.index = 2
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.label = 1
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.has_default_value = false
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.default_value = ''
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.type = 9
module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD.cpp_type = 9

module.DEPO_DEPO_LIMIT_LOCKED_FIELD.name = 'depo_limit_locked'
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_limit_locked'
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.number = 4
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.index = 3
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.label = 1
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.has_default_value = false
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.default_value = ''
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.type = 9
module.DEPO_DEPO_LIMIT_LOCKED_FIELD.cpp_type = 9

module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.name = 'depo_limit_available'
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_limit_available'
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.number = 5
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.index = 4
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.label = 1
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.has_default_value = false
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.default_value = ''
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.type = 9
module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD.cpp_type = 9

module.DEPO_DEPO_CURRENT_LIMIT_FIELD.name = 'depo_current_limit'
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_current_limit'
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.number = 6
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.index = 5
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.label = 1
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.has_default_value = false
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.default_value = ''
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.type = 9
module.DEPO_DEPO_CURRENT_LIMIT_FIELD.cpp_type = 9

module.DEPO_DEPO_OPEN_BALANCE_FIELD.name = 'depo_open_balance'
module.DEPO_DEPO_OPEN_BALANCE_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_open_balance'
module.DEPO_DEPO_OPEN_BALANCE_FIELD.number = 7
module.DEPO_DEPO_OPEN_BALANCE_FIELD.index = 6
module.DEPO_DEPO_OPEN_BALANCE_FIELD.label = 1
module.DEPO_DEPO_OPEN_BALANCE_FIELD.has_default_value = false
module.DEPO_DEPO_OPEN_BALANCE_FIELD.default_value = ''
module.DEPO_DEPO_OPEN_BALANCE_FIELD.type = 9
module.DEPO_DEPO_OPEN_BALANCE_FIELD.cpp_type = 9

module.DEPO_DEPO_OPEN_LIMIT_FIELD.name = 'depo_open_limit'
module.DEPO_DEPO_OPEN_LIMIT_FIELD.full_name = '.qlua.rpc.getDepo.Depo.depo_open_limit'
module.DEPO_DEPO_OPEN_LIMIT_FIELD.number = 8
module.DEPO_DEPO_OPEN_LIMIT_FIELD.index = 7
module.DEPO_DEPO_OPEN_LIMIT_FIELD.label = 1
module.DEPO_DEPO_OPEN_LIMIT_FIELD.has_default_value = false
module.DEPO_DEPO_OPEN_LIMIT_FIELD.default_value = ''
module.DEPO_DEPO_OPEN_LIMIT_FIELD.type = 9
module.DEPO_DEPO_OPEN_LIMIT_FIELD.cpp_type = 9

module.DEPO.name = 'Depo'
module.DEPO.full_name = '.qlua.rpc.getDepo.Depo'
module.DEPO.nested_types = {}
module.DEPO.enum_types = {}
module.DEPO.fields = {module.DEPO_DEPO_LIMIT_LOCKED_BUY_VALUE_FIELD, module.DEPO_DEPO_CURRENT_BALANCE_FIELD, module.DEPO_DEPO_LIMIT_LOCKED_BUY_FIELD, module.DEPO_DEPO_LIMIT_LOCKED_FIELD, module.DEPO_DEPO_LIMIT_AVAILABLE_FIELD, module.DEPO_DEPO_CURRENT_LIMIT_FIELD, module.DEPO_DEPO_OPEN_BALANCE_FIELD, module.DEPO_DEPO_OPEN_LIMIT_FIELD}
module.DEPO.is_extendable = false
module.DEPO.extensions = {}
module.REQUEST_CLIENT_CODE_FIELD.name = 'client_code'
module.REQUEST_CLIENT_CODE_FIELD.full_name = '.qlua.rpc.getDepo.Request.client_code'
module.REQUEST_CLIENT_CODE_FIELD.number = 1
module.REQUEST_CLIENT_CODE_FIELD.index = 0
module.REQUEST_CLIENT_CODE_FIELD.label = 1
module.REQUEST_CLIENT_CODE_FIELD.has_default_value = false
module.REQUEST_CLIENT_CODE_FIELD.default_value = ''
module.REQUEST_CLIENT_CODE_FIELD.type = 9
module.REQUEST_CLIENT_CODE_FIELD.cpp_type = 9

module.REQUEST_FIRMID_FIELD.name = 'firmid'
module.REQUEST_FIRMID_FIELD.full_name = '.qlua.rpc.getDepo.Request.firmid'
module.REQUEST_FIRMID_FIELD.number = 2
module.REQUEST_FIRMID_FIELD.index = 1
module.REQUEST_FIRMID_FIELD.label = 1
module.REQUEST_FIRMID_FIELD.has_default_value = false
module.REQUEST_FIRMID_FIELD.default_value = ''
module.REQUEST_FIRMID_FIELD.type = 9
module.REQUEST_FIRMID_FIELD.cpp_type = 9

module.REQUEST_SEC_CODE_FIELD.name = 'sec_code'
module.REQUEST_SEC_CODE_FIELD.full_name = '.qlua.rpc.getDepo.Request.sec_code'
module.REQUEST_SEC_CODE_FIELD.number = 3
module.REQUEST_SEC_CODE_FIELD.index = 2
module.REQUEST_SEC_CODE_FIELD.label = 1
module.REQUEST_SEC_CODE_FIELD.has_default_value = false
module.REQUEST_SEC_CODE_FIELD.default_value = ''
module.REQUEST_SEC_CODE_FIELD.type = 9
module.REQUEST_SEC_CODE_FIELD.cpp_type = 9

module.REQUEST_TRDACCID_FIELD.name = 'trdaccid'
module.REQUEST_TRDACCID_FIELD.full_name = '.qlua.rpc.getDepo.Request.trdaccid'
module.REQUEST_TRDACCID_FIELD.number = 4
module.REQUEST_TRDACCID_FIELD.index = 3
module.REQUEST_TRDACCID_FIELD.label = 1
module.REQUEST_TRDACCID_FIELD.has_default_value = false
module.REQUEST_TRDACCID_FIELD.default_value = ''
module.REQUEST_TRDACCID_FIELD.type = 9
module.REQUEST_TRDACCID_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getDepo.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CLIENT_CODE_FIELD, module.REQUEST_FIRMID_FIELD, module.REQUEST_SEC_CODE_FIELD, module.REQUEST_TRDACCID_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_DEPO_FIELD.name = 'depo'
module.RESULT_DEPO_FIELD.full_name = '.qlua.rpc.getDepo.Result.depo'
module.RESULT_DEPO_FIELD.number = 1
module.RESULT_DEPO_FIELD.index = 0
module.RESULT_DEPO_FIELD.label = 1
module.RESULT_DEPO_FIELD.has_default_value = false
module.RESULT_DEPO_FIELD.default_value = nil
module.RESULT_DEPO_FIELD.message_type = module.DEPO
module.RESULT_DEPO_FIELD.type = 11
module.RESULT_DEPO_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getDepo.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_DEPO_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Depo = protobuf.Message(module.DEPO)
module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Depo','Request','Result'}
module.ENUM_TYPES = {}

return module
