-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.MONEY = protobuf.Descriptor()
module.MONEY_MONEY_OPEN_LIMIT_FIELD = protobuf.FieldDescriptor()
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD = protobuf.FieldDescriptor()
module.MONEY_MONEY_LIMIT_LOCKED_FIELD = protobuf.FieldDescriptor()
module.MONEY_MONEY_OPEN_BALANCE_FIELD = protobuf.FieldDescriptor()
module.MONEY_MONEY_CURRENT_LIMIT_FIELD = protobuf.FieldDescriptor()
module.MONEY_MONEY_CURRENT_BALANCE_FIELD = protobuf.FieldDescriptor()
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD = protobuf.FieldDescriptor()
module.REQUEST = protobuf.Descriptor()
module.REQUEST_CLIENT_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_FIRMID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TAG_FIELD = protobuf.FieldDescriptor()
module.REQUEST_CURRCODE_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_MONEY_FIELD = protobuf.FieldDescriptor()

module.MONEY_MONEY_OPEN_LIMIT_FIELD.name = 'money_open_limit'
module.MONEY_MONEY_OPEN_LIMIT_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_open_limit'
module.MONEY_MONEY_OPEN_LIMIT_FIELD.number = 1
module.MONEY_MONEY_OPEN_LIMIT_FIELD.index = 0
module.MONEY_MONEY_OPEN_LIMIT_FIELD.label = 1
module.MONEY_MONEY_OPEN_LIMIT_FIELD.has_default_value = false
module.MONEY_MONEY_OPEN_LIMIT_FIELD.default_value = ''
module.MONEY_MONEY_OPEN_LIMIT_FIELD.type = 9
module.MONEY_MONEY_OPEN_LIMIT_FIELD.cpp_type = 9

module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.name = 'money_limit_locked_nonmarginal_value'
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_limit_locked_nonmarginal_value'
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.number = 2
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.index = 1
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.label = 1
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.has_default_value = false
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.default_value = ''
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.type = 9
module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD.cpp_type = 9

module.MONEY_MONEY_LIMIT_LOCKED_FIELD.name = 'money_limit_locked'
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_limit_locked'
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.number = 3
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.index = 2
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.label = 1
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.has_default_value = false
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.default_value = ''
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.type = 9
module.MONEY_MONEY_LIMIT_LOCKED_FIELD.cpp_type = 9

module.MONEY_MONEY_OPEN_BALANCE_FIELD.name = 'money_open_balance'
module.MONEY_MONEY_OPEN_BALANCE_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_open_balance'
module.MONEY_MONEY_OPEN_BALANCE_FIELD.number = 4
module.MONEY_MONEY_OPEN_BALANCE_FIELD.index = 3
module.MONEY_MONEY_OPEN_BALANCE_FIELD.label = 1
module.MONEY_MONEY_OPEN_BALANCE_FIELD.has_default_value = false
module.MONEY_MONEY_OPEN_BALANCE_FIELD.default_value = ''
module.MONEY_MONEY_OPEN_BALANCE_FIELD.type = 9
module.MONEY_MONEY_OPEN_BALANCE_FIELD.cpp_type = 9

module.MONEY_MONEY_CURRENT_LIMIT_FIELD.name = 'money_current_limit'
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_current_limit'
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.number = 5
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.index = 4
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.label = 1
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.has_default_value = false
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.default_value = ''
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.type = 9
module.MONEY_MONEY_CURRENT_LIMIT_FIELD.cpp_type = 9

module.MONEY_MONEY_CURRENT_BALANCE_FIELD.name = 'money_current_balance'
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_current_balance'
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.number = 6
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.index = 5
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.label = 1
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.has_default_value = false
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.default_value = ''
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.type = 9
module.MONEY_MONEY_CURRENT_BALANCE_FIELD.cpp_type = 9

module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.name = 'money_limit_available'
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.full_name = '.qlua.rpc.getMoney.Money.money_limit_available'
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.number = 7
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.index = 6
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.label = 1
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.has_default_value = false
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.default_value = ''
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.type = 9
module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD.cpp_type = 9

module.MONEY.name = 'Money'
module.MONEY.full_name = '.qlua.rpc.getMoney.Money'
module.MONEY.nested_types = {}
module.MONEY.enum_types = {}
module.MONEY.fields = {module.MONEY_MONEY_OPEN_LIMIT_FIELD, module.MONEY_MONEY_LIMIT_LOCKED_NONMARGINAL_VALUE_FIELD, module.MONEY_MONEY_LIMIT_LOCKED_FIELD, module.MONEY_MONEY_OPEN_BALANCE_FIELD, module.MONEY_MONEY_CURRENT_LIMIT_FIELD, module.MONEY_MONEY_CURRENT_BALANCE_FIELD, module.MONEY_MONEY_LIMIT_AVAILABLE_FIELD}
module.MONEY.is_extendable = false
module.MONEY.extensions = {}
module.REQUEST_CLIENT_CODE_FIELD.name = 'client_code'
module.REQUEST_CLIENT_CODE_FIELD.full_name = '.qlua.rpc.getMoney.Request.client_code'
module.REQUEST_CLIENT_CODE_FIELD.number = 1
module.REQUEST_CLIENT_CODE_FIELD.index = 0
module.REQUEST_CLIENT_CODE_FIELD.label = 1
module.REQUEST_CLIENT_CODE_FIELD.has_default_value = false
module.REQUEST_CLIENT_CODE_FIELD.default_value = ''
module.REQUEST_CLIENT_CODE_FIELD.type = 9
module.REQUEST_CLIENT_CODE_FIELD.cpp_type = 9

module.REQUEST_FIRMID_FIELD.name = 'firmid'
module.REQUEST_FIRMID_FIELD.full_name = '.qlua.rpc.getMoney.Request.firmid'
module.REQUEST_FIRMID_FIELD.number = 2
module.REQUEST_FIRMID_FIELD.index = 1
module.REQUEST_FIRMID_FIELD.label = 1
module.REQUEST_FIRMID_FIELD.has_default_value = false
module.REQUEST_FIRMID_FIELD.default_value = ''
module.REQUEST_FIRMID_FIELD.type = 9
module.REQUEST_FIRMID_FIELD.cpp_type = 9

module.REQUEST_TAG_FIELD.name = 'tag'
module.REQUEST_TAG_FIELD.full_name = '.qlua.rpc.getMoney.Request.tag'
module.REQUEST_TAG_FIELD.number = 3
module.REQUEST_TAG_FIELD.index = 2
module.REQUEST_TAG_FIELD.label = 1
module.REQUEST_TAG_FIELD.has_default_value = false
module.REQUEST_TAG_FIELD.default_value = ''
module.REQUEST_TAG_FIELD.type = 9
module.REQUEST_TAG_FIELD.cpp_type = 9

module.REQUEST_CURRCODE_FIELD.name = 'currcode'
module.REQUEST_CURRCODE_FIELD.full_name = '.qlua.rpc.getMoney.Request.currcode'
module.REQUEST_CURRCODE_FIELD.number = 4
module.REQUEST_CURRCODE_FIELD.index = 3
module.REQUEST_CURRCODE_FIELD.label = 1
module.REQUEST_CURRCODE_FIELD.has_default_value = false
module.REQUEST_CURRCODE_FIELD.default_value = ''
module.REQUEST_CURRCODE_FIELD.type = 9
module.REQUEST_CURRCODE_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getMoney.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CLIENT_CODE_FIELD, module.REQUEST_FIRMID_FIELD, module.REQUEST_TAG_FIELD, module.REQUEST_CURRCODE_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_MONEY_FIELD.name = 'money'
module.RESULT_MONEY_FIELD.full_name = '.qlua.rpc.getMoney.Result.money'
module.RESULT_MONEY_FIELD.number = 1
module.RESULT_MONEY_FIELD.index = 0
module.RESULT_MONEY_FIELD.label = 1
module.RESULT_MONEY_FIELD.has_default_value = false
module.RESULT_MONEY_FIELD.default_value = nil
module.RESULT_MONEY_FIELD.message_type = module.MONEY
module.RESULT_MONEY_FIELD.type = 11
module.RESULT_MONEY_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getMoney.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_MONEY_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Money = protobuf.Message(module.MONEY)
module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Money','Request','Result'}
module.ENUM_TYPES = {}

return module
