-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'
local imports = {}
imports['quik-lua-rpc/messages/qlua_structures_pb'] = require 'quik-lua-rpc/messages/qlua_structures_pb'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_CLASS_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_ORDER_ID_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_ORDER_FIELD = protobuf.FieldDescriptor()
module.RESULT_INDX_FIELD = protobuf.FieldDescriptor()

module.REQUEST_CLASS_CODE_FIELD.name = 'class_code'
module.REQUEST_CLASS_CODE_FIELD.full_name = '.qlua.rpc.getOrderByNumber.Request.class_code'
module.REQUEST_CLASS_CODE_FIELD.number = 1
module.REQUEST_CLASS_CODE_FIELD.index = 0
module.REQUEST_CLASS_CODE_FIELD.label = 1
module.REQUEST_CLASS_CODE_FIELD.has_default_value = false
module.REQUEST_CLASS_CODE_FIELD.default_value = ''
module.REQUEST_CLASS_CODE_FIELD.type = 9
module.REQUEST_CLASS_CODE_FIELD.cpp_type = 9

module.REQUEST_ORDER_ID_FIELD.name = 'order_id'
module.REQUEST_ORDER_ID_FIELD.full_name = '.qlua.rpc.getOrderByNumber.Request.order_id'
module.REQUEST_ORDER_ID_FIELD.number = 2
module.REQUEST_ORDER_ID_FIELD.index = 1
module.REQUEST_ORDER_ID_FIELD.label = 1
module.REQUEST_ORDER_ID_FIELD.has_default_value = false
module.REQUEST_ORDER_ID_FIELD.default_value = 0
module.REQUEST_ORDER_ID_FIELD.type = 13
module.REQUEST_ORDER_ID_FIELD.cpp_type = 3

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getOrderByNumber.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CLASS_CODE_FIELD, module.REQUEST_ORDER_ID_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_ORDER_FIELD.name = 'order'
module.RESULT_ORDER_FIELD.full_name = '.qlua.rpc.getOrderByNumber.Result.order'
module.RESULT_ORDER_FIELD.number = 1
module.RESULT_ORDER_FIELD.index = 0
module.RESULT_ORDER_FIELD.label = 1
module.RESULT_ORDER_FIELD.has_default_value = false
module.RESULT_ORDER_FIELD.default_value = nil
module.RESULT_ORDER_FIELD.message_type = imports['quik-lua-rpc/messages/qlua_structures_pb'].ORDER
module.RESULT_ORDER_FIELD.type = 11
module.RESULT_ORDER_FIELD.cpp_type = 10

module.RESULT_INDX_FIELD.name = 'indx'
module.RESULT_INDX_FIELD.full_name = '.qlua.rpc.getOrderByNumber.Result.indx'
module.RESULT_INDX_FIELD.number = 2
module.RESULT_INDX_FIELD.index = 1
module.RESULT_INDX_FIELD.label = 1
module.RESULT_INDX_FIELD.has_default_value = false
module.RESULT_INDX_FIELD.default_value = 0
module.RESULT_INDX_FIELD.type = 5
module.RESULT_INDX_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getOrderByNumber.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_ORDER_FIELD, module.RESULT_INDX_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
