-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'
local imports = {}
imports['quik-lua-rpc/messages/qlua_structures_pb'] = require 'quik-lua-rpc/messages/qlua_structures_pb'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_CLASS_CODE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_SEC_CODE_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_SECURITY_INFO_FIELD = protobuf.FieldDescriptor()

module.REQUEST_CLASS_CODE_FIELD.name = 'class_code'
module.REQUEST_CLASS_CODE_FIELD.full_name = '.qlua.rpc.getSecurityInfo.Request.class_code'
module.REQUEST_CLASS_CODE_FIELD.number = 1
module.REQUEST_CLASS_CODE_FIELD.index = 0
module.REQUEST_CLASS_CODE_FIELD.label = 1
module.REQUEST_CLASS_CODE_FIELD.has_default_value = false
module.REQUEST_CLASS_CODE_FIELD.default_value = ''
module.REQUEST_CLASS_CODE_FIELD.type = 9
module.REQUEST_CLASS_CODE_FIELD.cpp_type = 9

module.REQUEST_SEC_CODE_FIELD.name = 'sec_code'
module.REQUEST_SEC_CODE_FIELD.full_name = '.qlua.rpc.getSecurityInfo.Request.sec_code'
module.REQUEST_SEC_CODE_FIELD.number = 2
module.REQUEST_SEC_CODE_FIELD.index = 1
module.REQUEST_SEC_CODE_FIELD.label = 1
module.REQUEST_SEC_CODE_FIELD.has_default_value = false
module.REQUEST_SEC_CODE_FIELD.default_value = ''
module.REQUEST_SEC_CODE_FIELD.type = 9
module.REQUEST_SEC_CODE_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.getSecurityInfo.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_CLASS_CODE_FIELD, module.REQUEST_SEC_CODE_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_SECURITY_INFO_FIELD.name = 'security_info'
module.RESULT_SECURITY_INFO_FIELD.full_name = '.qlua.rpc.getSecurityInfo.Result.security_info'
module.RESULT_SECURITY_INFO_FIELD.number = 1
module.RESULT_SECURITY_INFO_FIELD.index = 0
module.RESULT_SECURITY_INFO_FIELD.label = 1
module.RESULT_SECURITY_INFO_FIELD.has_default_value = false
module.RESULT_SECURITY_INFO_FIELD.default_value = nil
module.RESULT_SECURITY_INFO_FIELD.message_type = imports['quik-lua-rpc/messages/qlua_structures_pb'].SECURITY
module.RESULT_SECURITY_INFO_FIELD.type = 11
module.RESULT_SECURITY_INFO_FIELD.cpp_type = 10

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getSecurityInfo.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_SECURITY_INFO_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
