-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_T_ID_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_ROWS_FIELD = protobuf.FieldDescriptor()
module.RESULT_COL_FIELD = protobuf.FieldDescriptor()

module.REQUEST_T_ID_FIELD.name = 't_id'
module.REQUEST_T_ID_FIELD.full_name = '.qlua.rpc.GetTableSize.Request.t_id'
module.REQUEST_T_ID_FIELD.number = 1
module.REQUEST_T_ID_FIELD.index = 0
module.REQUEST_T_ID_FIELD.label = 1
module.REQUEST_T_ID_FIELD.has_default_value = false
module.REQUEST_T_ID_FIELD.default_value = 0
module.REQUEST_T_ID_FIELD.type = 5
module.REQUEST_T_ID_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.GetTableSize.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_T_ID_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_ROWS_FIELD.name = 'rows'
module.RESULT_ROWS_FIELD.full_name = '.qlua.rpc.GetTableSize.Result.rows'
module.RESULT_ROWS_FIELD.number = 1
module.RESULT_ROWS_FIELD.index = 0
module.RESULT_ROWS_FIELD.label = 1
module.RESULT_ROWS_FIELD.has_default_value = false
module.RESULT_ROWS_FIELD.default_value = 0
module.RESULT_ROWS_FIELD.type = 5
module.RESULT_ROWS_FIELD.cpp_type = 1

module.RESULT_COL_FIELD.name = 'col'
module.RESULT_COL_FIELD.full_name = '.qlua.rpc.GetTableSize.Result.col'
module.RESULT_COL_FIELD.number = 2
module.RESULT_COL_FIELD.index = 1
module.RESULT_COL_FIELD.label = 1
module.RESULT_COL_FIELD.has_default_value = false
module.RESULT_COL_FIELD.default_value = 0
module.RESULT_COL_FIELD.type = 5
module.RESULT_COL_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.GetTableSize.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_ROWS_FIELD, module.RESULT_COL_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
