-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.RESULT = protobuf.Descriptor()
module.RESULT_WORKING_FOLDER_FIELD = protobuf.FieldDescriptor()

module.RESULT_WORKING_FOLDER_FIELD.name = 'working_folder'
module.RESULT_WORKING_FOLDER_FIELD.full_name = '.qlua.rpc.getWorkingFolder.Result.working_folder'
module.RESULT_WORKING_FOLDER_FIELD.number = 1
module.RESULT_WORKING_FOLDER_FIELD.index = 0
module.RESULT_WORKING_FOLDER_FIELD.label = 1
module.RESULT_WORKING_FOLDER_FIELD.has_default_value = false
module.RESULT_WORKING_FOLDER_FIELD.default_value = ''
module.RESULT_WORKING_FOLDER_FIELD.type = 9
module.RESULT_WORKING_FOLDER_FIELD.cpp_type = 9

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.getWorkingFolder.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_WORKING_FOLDER_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Result'}
module.ENUM_TYPES = {}

return module
