-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_T_ID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_ROW_FIELD = protobuf.FieldDescriptor()
module.REQUEST_COL_FIELD = protobuf.FieldDescriptor()
module.REQUEST_B_COLOR_FIELD = protobuf.FieldDescriptor()
module.REQUEST_F_COLOR_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TIMEOUT_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_T_ID_FIELD.name = 't_id'
module.REQUEST_T_ID_FIELD.full_name = '.qlua.rpc.Highlight.Request.t_id'
module.REQUEST_T_ID_FIELD.number = 1
module.REQUEST_T_ID_FIELD.index = 0
module.REQUEST_T_ID_FIELD.label = 1
module.REQUEST_T_ID_FIELD.has_default_value = false
module.REQUEST_T_ID_FIELD.default_value = 0
module.REQUEST_T_ID_FIELD.type = 5
module.REQUEST_T_ID_FIELD.cpp_type = 1

module.REQUEST_ROW_FIELD.name = 'row'
module.REQUEST_ROW_FIELD.full_name = '.qlua.rpc.Highlight.Request.row'
module.REQUEST_ROW_FIELD.number = 2
module.REQUEST_ROW_FIELD.index = 1
module.REQUEST_ROW_FIELD.label = 1
module.REQUEST_ROW_FIELD.has_default_value = false
module.REQUEST_ROW_FIELD.default_value = 0
module.REQUEST_ROW_FIELD.type = 5
module.REQUEST_ROW_FIELD.cpp_type = 1

module.REQUEST_COL_FIELD.name = 'col'
module.REQUEST_COL_FIELD.full_name = '.qlua.rpc.Highlight.Request.col'
module.REQUEST_COL_FIELD.number = 3
module.REQUEST_COL_FIELD.index = 2
module.REQUEST_COL_FIELD.label = 1
module.REQUEST_COL_FIELD.has_default_value = false
module.REQUEST_COL_FIELD.default_value = 0
module.REQUEST_COL_FIELD.type = 5
module.REQUEST_COL_FIELD.cpp_type = 1

module.REQUEST_B_COLOR_FIELD.name = 'b_color'
module.REQUEST_B_COLOR_FIELD.full_name = '.qlua.rpc.Highlight.Request.b_color'
module.REQUEST_B_COLOR_FIELD.number = 4
module.REQUEST_B_COLOR_FIELD.index = 3
module.REQUEST_B_COLOR_FIELD.label = 1
module.REQUEST_B_COLOR_FIELD.has_default_value = false
module.REQUEST_B_COLOR_FIELD.default_value = 0
module.REQUEST_B_COLOR_FIELD.type = 5
module.REQUEST_B_COLOR_FIELD.cpp_type = 1

module.REQUEST_F_COLOR_FIELD.name = 'f_color'
module.REQUEST_F_COLOR_FIELD.full_name = '.qlua.rpc.Highlight.Request.f_color'
module.REQUEST_F_COLOR_FIELD.number = 5
module.REQUEST_F_COLOR_FIELD.index = 4
module.REQUEST_F_COLOR_FIELD.label = 1
module.REQUEST_F_COLOR_FIELD.has_default_value = false
module.REQUEST_F_COLOR_FIELD.default_value = 0
module.REQUEST_F_COLOR_FIELD.type = 5
module.REQUEST_F_COLOR_FIELD.cpp_type = 1

module.REQUEST_TIMEOUT_FIELD.name = 'timeout'
module.REQUEST_TIMEOUT_FIELD.full_name = '.qlua.rpc.Highlight.Request.timeout'
module.REQUEST_TIMEOUT_FIELD.number = 6
module.REQUEST_TIMEOUT_FIELD.index = 5
module.REQUEST_TIMEOUT_FIELD.label = 1
module.REQUEST_TIMEOUT_FIELD.has_default_value = false
module.REQUEST_TIMEOUT_FIELD.default_value = 0
module.REQUEST_TIMEOUT_FIELD.type = 3
module.REQUEST_TIMEOUT_FIELD.cpp_type = 2

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.Highlight.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_T_ID_FIELD, module.REQUEST_ROW_FIELD, module.REQUEST_COL_FIELD, module.REQUEST_B_COLOR_FIELD, module.REQUEST_F_COLOR_FIELD, module.REQUEST_TIMEOUT_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.Highlight.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = false
module.RESULT_RESULT_FIELD.type = 8
module.RESULT_RESULT_FIELD.cpp_type = 7

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.Highlight.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
