-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.RESULT = protobuf.Descriptor()
module.RESULT_IS_CONNECTED_FIELD = protobuf.FieldDescriptor()

module.RESULT_IS_CONNECTED_FIELD.name = 'is_connected'
module.RESULT_IS_CONNECTED_FIELD.full_name = '.qlua.rpc.isConnected.Result.is_connected'
module.RESULT_IS_CONNECTED_FIELD.number = 1
module.RESULT_IS_CONNECTED_FIELD.index = 0
module.RESULT_IS_CONNECTED_FIELD.label = 1
module.RESULT_IS_CONNECTED_FIELD.has_default_value = false
module.RESULT_IS_CONNECTED_FIELD.default_value = 0
module.RESULT_IS_CONNECTED_FIELD.type = 5
module.RESULT_IS_CONNECTED_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.isConnected.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_IS_CONNECTED_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Result'}
module.ENUM_TYPES = {}

return module
