-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.ICONTYPE = protobuf.EnumDescriptor()
module.ICONTYPE_UNDEFINED_ENUM = protobuf.EnumValueDescriptor()
module.ICONTYPE_INFO_ENUM = protobuf.EnumValueDescriptor()
module.ICONTYPE_WARNING_ENUM = protobuf.EnumValueDescriptor()
module.ICONTYPE_ERROR_ENUM = protobuf.EnumValueDescriptor()
module.REQUEST = protobuf.Descriptor()
module.REQUEST_MESSAGE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_ICON_TYPE_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.ICONTYPE_UNDEFINED_ENUM.name = 'UNDEFINED'
module.ICONTYPE_UNDEFINED_ENUM.index = 0
module.ICONTYPE_UNDEFINED_ENUM.number = 0
module.ICONTYPE_INFO_ENUM.name = 'INFO'
module.ICONTYPE_INFO_ENUM.index = 1
module.ICONTYPE_INFO_ENUM.number = 1
module.ICONTYPE_WARNING_ENUM.name = 'WARNING'
module.ICONTYPE_WARNING_ENUM.index = 2
module.ICONTYPE_WARNING_ENUM.number = 2
module.ICONTYPE_ERROR_ENUM.name = 'ERROR'
module.ICONTYPE_ERROR_ENUM.index = 3
module.ICONTYPE_ERROR_ENUM.number = 3
module.ICONTYPE.name = 'IconType'
module.ICONTYPE.full_name = '.qlua.procs.IconType'
module.ICONTYPE.values = {module.ICONTYPE_UNDEFINED_ENUM,module.ICONTYPE_INFO_ENUM,module.ICONTYPE_WARNING_ENUM,module.ICONTYPE_ERROR_ENUM}
module.REQUEST_MESSAGE_FIELD.name = 'message'
module.REQUEST_MESSAGE_FIELD.full_name = '.qlua.procs.Request.message'
module.REQUEST_MESSAGE_FIELD.number = 1
module.REQUEST_MESSAGE_FIELD.index = 0
module.REQUEST_MESSAGE_FIELD.label = 1
module.REQUEST_MESSAGE_FIELD.has_default_value = false
module.REQUEST_MESSAGE_FIELD.default_value = ''
module.REQUEST_MESSAGE_FIELD.type = 9
module.REQUEST_MESSAGE_FIELD.cpp_type = 9

module.REQUEST_ICON_TYPE_FIELD.name = 'icon_type'
module.REQUEST_ICON_TYPE_FIELD.full_name = '.qlua.procs.Request.icon_type'
module.REQUEST_ICON_TYPE_FIELD.number = 2
module.REQUEST_ICON_TYPE_FIELD.index = 1
module.REQUEST_ICON_TYPE_FIELD.label = 1
module.REQUEST_ICON_TYPE_FIELD.has_default_value = false
module.REQUEST_ICON_TYPE_FIELD.default_value = nil
module.REQUEST_ICON_TYPE_FIELD.enum_type = module.ICONTYPE
module.REQUEST_ICON_TYPE_FIELD.type = 14
module.REQUEST_ICON_TYPE_FIELD.cpp_type = 8

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.procs.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_MESSAGE_FIELD, module.REQUEST_ICON_TYPE_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.procs.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = 0
module.RESULT_RESULT_FIELD.type = 5
module.RESULT_RESULT_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.procs.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.IconType = {}
module.IconType.ERROR = 3
module.IconType.INFO = 1
module.IconType.UNDEFINED = 0
module.IconType.WARNING = 2
module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {'IconType'}

return module
