-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.DATETIMEENTRY = protobuf.Descriptor()
module.DATETIMEENTRY_MCS_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_MS_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_SEC_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_MIN_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_HOUR_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_DAY_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_WEEK_DAY_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_MONTH_FIELD = protobuf.FieldDescriptor()
module.DATETIMEENTRY_YEAR_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY = protobuf.Descriptor()
module.CANDLEENTRY_OPEN_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY_CLOSE_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY_HIGH_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY_LOW_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY_VOLUME_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY_DOES_EXIST_FIELD = protobuf.FieldDescriptor()
module.CANDLEENTRY_DATETIME_FIELD = protobuf.FieldDescriptor()
module.TABLEENTRY = protobuf.Descriptor()
module.TABLEENTRY_K_FIELD = protobuf.FieldDescriptor()
module.TABLEENTRY_V_FIELD = protobuf.FieldDescriptor()

module.DATETIMEENTRY_MCS_FIELD.name = 'mcs'
module.DATETIMEENTRY_MCS_FIELD.full_name = '.qlua.types.DateTimeEntry.mcs'
module.DATETIMEENTRY_MCS_FIELD.number = 1
module.DATETIMEENTRY_MCS_FIELD.index = 0
module.DATETIMEENTRY_MCS_FIELD.label = 1
module.DATETIMEENTRY_MCS_FIELD.has_default_value = false
module.DATETIMEENTRY_MCS_FIELD.default_value = ''
module.DATETIMEENTRY_MCS_FIELD.type = 9
module.DATETIMEENTRY_MCS_FIELD.cpp_type = 9

module.DATETIMEENTRY_MS_FIELD.name = 'ms'
module.DATETIMEENTRY_MS_FIELD.full_name = '.qlua.types.DateTimeEntry.ms'
module.DATETIMEENTRY_MS_FIELD.number = 2
module.DATETIMEENTRY_MS_FIELD.index = 1
module.DATETIMEENTRY_MS_FIELD.label = 1
module.DATETIMEENTRY_MS_FIELD.has_default_value = false
module.DATETIMEENTRY_MS_FIELD.default_value = ''
module.DATETIMEENTRY_MS_FIELD.type = 9
module.DATETIMEENTRY_MS_FIELD.cpp_type = 9

module.DATETIMEENTRY_SEC_FIELD.name = 'sec'
module.DATETIMEENTRY_SEC_FIELD.full_name = '.qlua.types.DateTimeEntry.sec'
module.DATETIMEENTRY_SEC_FIELD.number = 3
module.DATETIMEENTRY_SEC_FIELD.index = 2
module.DATETIMEENTRY_SEC_FIELD.label = 1
module.DATETIMEENTRY_SEC_FIELD.has_default_value = false
module.DATETIMEENTRY_SEC_FIELD.default_value = 0
module.DATETIMEENTRY_SEC_FIELD.type = 5
module.DATETIMEENTRY_SEC_FIELD.cpp_type = 1

module.DATETIMEENTRY_MIN_FIELD.name = 'min'
module.DATETIMEENTRY_MIN_FIELD.full_name = '.qlua.types.DateTimeEntry.min'
module.DATETIMEENTRY_MIN_FIELD.number = 4
module.DATETIMEENTRY_MIN_FIELD.index = 3
module.DATETIMEENTRY_MIN_FIELD.label = 1
module.DATETIMEENTRY_MIN_FIELD.has_default_value = false
module.DATETIMEENTRY_MIN_FIELD.default_value = 0
module.DATETIMEENTRY_MIN_FIELD.type = 5
module.DATETIMEENTRY_MIN_FIELD.cpp_type = 1

module.DATETIMEENTRY_HOUR_FIELD.name = 'hour'
module.DATETIMEENTRY_HOUR_FIELD.full_name = '.qlua.types.DateTimeEntry.hour'
module.DATETIMEENTRY_HOUR_FIELD.number = 5
module.DATETIMEENTRY_HOUR_FIELD.index = 4
module.DATETIMEENTRY_HOUR_FIELD.label = 1
module.DATETIMEENTRY_HOUR_FIELD.has_default_value = false
module.DATETIMEENTRY_HOUR_FIELD.default_value = 0
module.DATETIMEENTRY_HOUR_FIELD.type = 5
module.DATETIMEENTRY_HOUR_FIELD.cpp_type = 1

module.DATETIMEENTRY_DAY_FIELD.name = 'day'
module.DATETIMEENTRY_DAY_FIELD.full_name = '.qlua.types.DateTimeEntry.day'
module.DATETIMEENTRY_DAY_FIELD.number = 6
module.DATETIMEENTRY_DAY_FIELD.index = 5
module.DATETIMEENTRY_DAY_FIELD.label = 1
module.DATETIMEENTRY_DAY_FIELD.has_default_value = false
module.DATETIMEENTRY_DAY_FIELD.default_value = 0
module.DATETIMEENTRY_DAY_FIELD.type = 5
module.DATETIMEENTRY_DAY_FIELD.cpp_type = 1

module.DATETIMEENTRY_WEEK_DAY_FIELD.name = 'week_day'
module.DATETIMEENTRY_WEEK_DAY_FIELD.full_name = '.qlua.types.DateTimeEntry.week_day'
module.DATETIMEENTRY_WEEK_DAY_FIELD.number = 7
module.DATETIMEENTRY_WEEK_DAY_FIELD.index = 6
module.DATETIMEENTRY_WEEK_DAY_FIELD.label = 1
module.DATETIMEENTRY_WEEK_DAY_FIELD.has_default_value = false
module.DATETIMEENTRY_WEEK_DAY_FIELD.default_value = 0
module.DATETIMEENTRY_WEEK_DAY_FIELD.type = 5
module.DATETIMEENTRY_WEEK_DAY_FIELD.cpp_type = 1

module.DATETIMEENTRY_MONTH_FIELD.name = 'month'
module.DATETIMEENTRY_MONTH_FIELD.full_name = '.qlua.types.DateTimeEntry.month'
module.DATETIMEENTRY_MONTH_FIELD.number = 8
module.DATETIMEENTRY_MONTH_FIELD.index = 7
module.DATETIMEENTRY_MONTH_FIELD.label = 1
module.DATETIMEENTRY_MONTH_FIELD.has_default_value = false
module.DATETIMEENTRY_MONTH_FIELD.default_value = 0
module.DATETIMEENTRY_MONTH_FIELD.type = 5
module.DATETIMEENTRY_MONTH_FIELD.cpp_type = 1

module.DATETIMEENTRY_YEAR_FIELD.name = 'year'
module.DATETIMEENTRY_YEAR_FIELD.full_name = '.qlua.types.DateTimeEntry.year'
module.DATETIMEENTRY_YEAR_FIELD.number = 9
module.DATETIMEENTRY_YEAR_FIELD.index = 8
module.DATETIMEENTRY_YEAR_FIELD.label = 1
module.DATETIMEENTRY_YEAR_FIELD.has_default_value = false
module.DATETIMEENTRY_YEAR_FIELD.default_value = 0
module.DATETIMEENTRY_YEAR_FIELD.type = 5
module.DATETIMEENTRY_YEAR_FIELD.cpp_type = 1

module.DATETIMEENTRY.name = 'DateTimeEntry'
module.DATETIMEENTRY.full_name = '.qlua.types.DateTimeEntry'
module.DATETIMEENTRY.nested_types = {}
module.DATETIMEENTRY.enum_types = {}
module.DATETIMEENTRY.fields = {module.DATETIMEENTRY_MCS_FIELD, module.DATETIMEENTRY_MS_FIELD, module.DATETIMEENTRY_SEC_FIELD, module.DATETIMEENTRY_MIN_FIELD, module.DATETIMEENTRY_HOUR_FIELD, module.DATETIMEENTRY_DAY_FIELD, module.DATETIMEENTRY_WEEK_DAY_FIELD, module.DATETIMEENTRY_MONTH_FIELD, module.DATETIMEENTRY_YEAR_FIELD}
module.DATETIMEENTRY.is_extendable = false
module.DATETIMEENTRY.extensions = {}
module.CANDLEENTRY_OPEN_FIELD.name = 'open'
module.CANDLEENTRY_OPEN_FIELD.full_name = '.qlua.types.CandleEntry.open'
module.CANDLEENTRY_OPEN_FIELD.number = 1
module.CANDLEENTRY_OPEN_FIELD.index = 0
module.CANDLEENTRY_OPEN_FIELD.label = 1
module.CANDLEENTRY_OPEN_FIELD.has_default_value = false
module.CANDLEENTRY_OPEN_FIELD.default_value = ''
module.CANDLEENTRY_OPEN_FIELD.type = 9
module.CANDLEENTRY_OPEN_FIELD.cpp_type = 9

module.CANDLEENTRY_CLOSE_FIELD.name = 'close'
module.CANDLEENTRY_CLOSE_FIELD.full_name = '.qlua.types.CandleEntry.close'
module.CANDLEENTRY_CLOSE_FIELD.number = 2
module.CANDLEENTRY_CLOSE_FIELD.index = 1
module.CANDLEENTRY_CLOSE_FIELD.label = 1
module.CANDLEENTRY_CLOSE_FIELD.has_default_value = false
module.CANDLEENTRY_CLOSE_FIELD.default_value = ''
module.CANDLEENTRY_CLOSE_FIELD.type = 9
module.CANDLEENTRY_CLOSE_FIELD.cpp_type = 9

module.CANDLEENTRY_HIGH_FIELD.name = 'high'
module.CANDLEENTRY_HIGH_FIELD.full_name = '.qlua.types.CandleEntry.high'
module.CANDLEENTRY_HIGH_FIELD.number = 3
module.CANDLEENTRY_HIGH_FIELD.index = 2
module.CANDLEENTRY_HIGH_FIELD.label = 1
module.CANDLEENTRY_HIGH_FIELD.has_default_value = false
module.CANDLEENTRY_HIGH_FIELD.default_value = ''
module.CANDLEENTRY_HIGH_FIELD.type = 9
module.CANDLEENTRY_HIGH_FIELD.cpp_type = 9

module.CANDLEENTRY_LOW_FIELD.name = 'low'
module.CANDLEENTRY_LOW_FIELD.full_name = '.qlua.types.CandleEntry.low'
module.CANDLEENTRY_LOW_FIELD.number = 4
module.CANDLEENTRY_LOW_FIELD.index = 3
module.CANDLEENTRY_LOW_FIELD.label = 1
module.CANDLEENTRY_LOW_FIELD.has_default_value = false
module.CANDLEENTRY_LOW_FIELD.default_value = ''
module.CANDLEENTRY_LOW_FIELD.type = 9
module.CANDLEENTRY_LOW_FIELD.cpp_type = 9

module.CANDLEENTRY_VOLUME_FIELD.name = 'volume'
module.CANDLEENTRY_VOLUME_FIELD.full_name = '.qlua.types.CandleEntry.volume'
module.CANDLEENTRY_VOLUME_FIELD.number = 5
module.CANDLEENTRY_VOLUME_FIELD.index = 4
module.CANDLEENTRY_VOLUME_FIELD.label = 1
module.CANDLEENTRY_VOLUME_FIELD.has_default_value = false
module.CANDLEENTRY_VOLUME_FIELD.default_value = ''
module.CANDLEENTRY_VOLUME_FIELD.type = 9
module.CANDLEENTRY_VOLUME_FIELD.cpp_type = 9

module.CANDLEENTRY_DOES_EXIST_FIELD.name = 'does_exist'
module.CANDLEENTRY_DOES_EXIST_FIELD.full_name = '.qlua.types.CandleEntry.does_exist'
module.CANDLEENTRY_DOES_EXIST_FIELD.number = 6
module.CANDLEENTRY_DOES_EXIST_FIELD.index = 5
module.CANDLEENTRY_DOES_EXIST_FIELD.label = 1
module.CANDLEENTRY_DOES_EXIST_FIELD.has_default_value = false
module.CANDLEENTRY_DOES_EXIST_FIELD.default_value = 0
module.CANDLEENTRY_DOES_EXIST_FIELD.type = 5
module.CANDLEENTRY_DOES_EXIST_FIELD.cpp_type = 1

module.CANDLEENTRY_DATETIME_FIELD.name = 'datetime'
module.CANDLEENTRY_DATETIME_FIELD.full_name = '.qlua.types.CandleEntry.datetime'
module.CANDLEENTRY_DATETIME_FIELD.number = 7
module.CANDLEENTRY_DATETIME_FIELD.index = 6
module.CANDLEENTRY_DATETIME_FIELD.label = 1
module.CANDLEENTRY_DATETIME_FIELD.has_default_value = false
module.CANDLEENTRY_DATETIME_FIELD.default_value = nil
module.CANDLEENTRY_DATETIME_FIELD.message_type = module.DATETIMEENTRY
module.CANDLEENTRY_DATETIME_FIELD.type = 11
module.CANDLEENTRY_DATETIME_FIELD.cpp_type = 10

module.CANDLEENTRY.name = 'CandleEntry'
module.CANDLEENTRY.full_name = '.qlua.types.CandleEntry'
module.CANDLEENTRY.nested_types = {}
module.CANDLEENTRY.enum_types = {}
module.CANDLEENTRY.fields = {module.CANDLEENTRY_OPEN_FIELD, module.CANDLEENTRY_CLOSE_FIELD, module.CANDLEENTRY_HIGH_FIELD, module.CANDLEENTRY_LOW_FIELD, module.CANDLEENTRY_VOLUME_FIELD, module.CANDLEENTRY_DOES_EXIST_FIELD, module.CANDLEENTRY_DATETIME_FIELD}
module.CANDLEENTRY.is_extendable = false
module.CANDLEENTRY.extensions = {}
module.TABLEENTRY_K_FIELD.name = 'k'
module.TABLEENTRY_K_FIELD.full_name = '.qlua.types.TableEntry.k'
module.TABLEENTRY_K_FIELD.number = 1
module.TABLEENTRY_K_FIELD.index = 0
module.TABLEENTRY_K_FIELD.label = 1
module.TABLEENTRY_K_FIELD.has_default_value = false
module.TABLEENTRY_K_FIELD.default_value = ''
module.TABLEENTRY_K_FIELD.type = 9
module.TABLEENTRY_K_FIELD.cpp_type = 9

module.TABLEENTRY_V_FIELD.name = 'v'
module.TABLEENTRY_V_FIELD.full_name = '.qlua.types.TableEntry.v'
module.TABLEENTRY_V_FIELD.number = 2
module.TABLEENTRY_V_FIELD.index = 1
module.TABLEENTRY_V_FIELD.label = 1
module.TABLEENTRY_V_FIELD.has_default_value = false
module.TABLEENTRY_V_FIELD.default_value = ''
module.TABLEENTRY_V_FIELD.type = 9
module.TABLEENTRY_V_FIELD.cpp_type = 9

module.TABLEENTRY.name = 'TableEntry'
module.TABLEENTRY.full_name = '.qlua.types.TableEntry'
module.TABLEENTRY.nested_types = {}
module.TABLEENTRY.enum_types = {}
module.TABLEENTRY.fields = {module.TABLEENTRY_K_FIELD, module.TABLEENTRY_V_FIELD}
module.TABLEENTRY.is_extendable = false
module.TABLEENTRY.extensions = {}

module.CandleEntry = protobuf.Message(module.CANDLEENTRY)
module.DateTimeEntry = protobuf.Message(module.DATETIMEENTRY)
module.TableEntry = protobuf.Message(module.TABLEENTRY)


module.MESSAGE_TYPES = {'DateTimeEntry','CandleEntry','TableEntry'}
module.ENUM_TYPES = {}

return module
