-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_RED_FIELD = protobuf.FieldDescriptor()
module.REQUEST_GREEN_FIELD = protobuf.FieldDescriptor()
module.REQUEST_BLUE_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_RED_FIELD.name = 'red'
module.REQUEST_RED_FIELD.full_name = '.qlua.rpc.RGB.Request.red'
module.REQUEST_RED_FIELD.number = 1
module.REQUEST_RED_FIELD.index = 0
module.REQUEST_RED_FIELD.label = 1
module.REQUEST_RED_FIELD.has_default_value = false
module.REQUEST_RED_FIELD.default_value = 0
module.REQUEST_RED_FIELD.type = 5
module.REQUEST_RED_FIELD.cpp_type = 1

module.REQUEST_GREEN_FIELD.name = 'green'
module.REQUEST_GREEN_FIELD.full_name = '.qlua.rpc.RGB.Request.green'
module.REQUEST_GREEN_FIELD.number = 2
module.REQUEST_GREEN_FIELD.index = 1
module.REQUEST_GREEN_FIELD.label = 1
module.REQUEST_GREEN_FIELD.has_default_value = false
module.REQUEST_GREEN_FIELD.default_value = 0
module.REQUEST_GREEN_FIELD.type = 5
module.REQUEST_GREEN_FIELD.cpp_type = 1

module.REQUEST_BLUE_FIELD.name = 'blue'
module.REQUEST_BLUE_FIELD.full_name = '.qlua.rpc.RGB.Request.blue'
module.REQUEST_BLUE_FIELD.number = 3
module.REQUEST_BLUE_FIELD.index = 2
module.REQUEST_BLUE_FIELD.label = 1
module.REQUEST_BLUE_FIELD.has_default_value = false
module.REQUEST_BLUE_FIELD.default_value = 0
module.REQUEST_BLUE_FIELD.type = 5
module.REQUEST_BLUE_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.RGB.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_RED_FIELD, module.REQUEST_GREEN_FIELD, module.REQUEST_BLUE_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.RGB.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = 0
module.RESULT_RESULT_FIELD.type = 5
module.RESULT_RESULT_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.RGB.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
