-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_TABLE_NAME_FIELD = protobuf.FieldDescriptor()
module.REQUEST_START_INDEX_FIELD = protobuf.FieldDescriptor()
module.REQUEST_END_INDEX_FIELD = protobuf.FieldDescriptor()
module.REQUEST_FN_DEF_FIELD = protobuf.FieldDescriptor()
module.REQUEST_PARAMS_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_ITEMS_INDICES_FIELD = protobuf.FieldDescriptor()

module.REQUEST_TABLE_NAME_FIELD.name = 'table_name'
module.REQUEST_TABLE_NAME_FIELD.full_name = '.qlua.rpc.SearchItems.Request.table_name'
module.REQUEST_TABLE_NAME_FIELD.number = 1
module.REQUEST_TABLE_NAME_FIELD.index = 0
module.REQUEST_TABLE_NAME_FIELD.label = 1
module.REQUEST_TABLE_NAME_FIELD.has_default_value = false
module.REQUEST_TABLE_NAME_FIELD.default_value = ''
module.REQUEST_TABLE_NAME_FIELD.type = 9
module.REQUEST_TABLE_NAME_FIELD.cpp_type = 9

module.REQUEST_START_INDEX_FIELD.name = 'start_index'
module.REQUEST_START_INDEX_FIELD.full_name = '.qlua.rpc.SearchItems.Request.start_index'
module.REQUEST_START_INDEX_FIELD.number = 2
module.REQUEST_START_INDEX_FIELD.index = 1
module.REQUEST_START_INDEX_FIELD.label = 1
module.REQUEST_START_INDEX_FIELD.has_default_value = false
module.REQUEST_START_INDEX_FIELD.default_value = 0
module.REQUEST_START_INDEX_FIELD.type = 5
module.REQUEST_START_INDEX_FIELD.cpp_type = 1

module.REQUEST_END_INDEX_FIELD.name = 'end_index'
module.REQUEST_END_INDEX_FIELD.full_name = '.qlua.rpc.SearchItems.Request.end_index'
module.REQUEST_END_INDEX_FIELD.number = 3
module.REQUEST_END_INDEX_FIELD.index = 2
module.REQUEST_END_INDEX_FIELD.label = 1
module.REQUEST_END_INDEX_FIELD.has_default_value = false
module.REQUEST_END_INDEX_FIELD.default_value = 0
module.REQUEST_END_INDEX_FIELD.type = 5
module.REQUEST_END_INDEX_FIELD.cpp_type = 1

module.REQUEST_FN_DEF_FIELD.name = 'fn_def'
module.REQUEST_FN_DEF_FIELD.full_name = '.qlua.rpc.SearchItems.Request.fn_def'
module.REQUEST_FN_DEF_FIELD.number = 4
module.REQUEST_FN_DEF_FIELD.index = 3
module.REQUEST_FN_DEF_FIELD.label = 1
module.REQUEST_FN_DEF_FIELD.has_default_value = false
module.REQUEST_FN_DEF_FIELD.default_value = ''
module.REQUEST_FN_DEF_FIELD.type = 9
module.REQUEST_FN_DEF_FIELD.cpp_type = 9

module.REQUEST_PARAMS_FIELD.name = 'params'
module.REQUEST_PARAMS_FIELD.full_name = '.qlua.rpc.SearchItems.Request.params'
module.REQUEST_PARAMS_FIELD.number = 5
module.REQUEST_PARAMS_FIELD.index = 4
module.REQUEST_PARAMS_FIELD.label = 1
module.REQUEST_PARAMS_FIELD.has_default_value = false
module.REQUEST_PARAMS_FIELD.default_value = ''
module.REQUEST_PARAMS_FIELD.type = 9
module.REQUEST_PARAMS_FIELD.cpp_type = 9

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.SearchItems.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_TABLE_NAME_FIELD, module.REQUEST_START_INDEX_FIELD, module.REQUEST_END_INDEX_FIELD, module.REQUEST_FN_DEF_FIELD, module.REQUEST_PARAMS_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_ITEMS_INDICES_FIELD.name = 'items_indices'
module.RESULT_ITEMS_INDICES_FIELD.full_name = '.qlua.rpc.SearchItems.Result.items_indices'
module.RESULT_ITEMS_INDICES_FIELD.number = 1
module.RESULT_ITEMS_INDICES_FIELD.index = 0
module.RESULT_ITEMS_INDICES_FIELD.label = 3
module.RESULT_ITEMS_INDICES_FIELD.has_default_value = false
module.RESULT_ITEMS_INDICES_FIELD.default_value = {}
module.RESULT_ITEMS_INDICES_FIELD.type = 5
module.RESULT_ITEMS_INDICES_FIELD.cpp_type = 1

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.SearchItems.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_ITEMS_INDICES_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
