-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_TRANSACTIONENTRY = protobuf.Descriptor()
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD = protobuf.FieldDescriptor()
module.REQUEST_TRANSACTION_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.name = 'key'
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.full_name = '.qlua.rpc.sendTransaction.Request.TransactionEntry.key'
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.number = 1
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.index = 0
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.label = 1
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.has_default_value = false
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.default_value = ''
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.type = 9
module.REQUEST_TRANSACTIONENTRY_KEY_FIELD.cpp_type = 9

module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.name = 'value'
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.full_name = '.qlua.rpc.sendTransaction.Request.TransactionEntry.value'
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.number = 2
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.index = 1
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.label = 1
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.has_default_value = false
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.default_value = ''
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.type = 9
module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD.cpp_type = 9

module.REQUEST_TRANSACTIONENTRY.name = 'TransactionEntry'
module.REQUEST_TRANSACTIONENTRY.full_name = '.qlua.rpc.sendTransaction.Request.TransactionEntry'
module.REQUEST_TRANSACTIONENTRY.nested_types = {}
module.REQUEST_TRANSACTIONENTRY.enum_types = {}
module.REQUEST_TRANSACTIONENTRY.fields = {module.REQUEST_TRANSACTIONENTRY_KEY_FIELD, module.REQUEST_TRANSACTIONENTRY_VALUE_FIELD}
module.REQUEST_TRANSACTIONENTRY.is_extendable = false
module.REQUEST_TRANSACTIONENTRY.extensions = {}
module.REQUEST_TRANSACTIONENTRY.containing_type = REQUEST
module.REQUEST_TRANSACTION_FIELD.name = 'transaction'
module.REQUEST_TRANSACTION_FIELD.full_name = '.qlua.rpc.sendTransaction.Request.transaction'
module.REQUEST_TRANSACTION_FIELD.number = 1
module.REQUEST_TRANSACTION_FIELD.index = 0
module.REQUEST_TRANSACTION_FIELD.label = 3
module.REQUEST_TRANSACTION_FIELD.has_default_value = false
module.REQUEST_TRANSACTION_FIELD.default_value = {}
module.REQUEST_TRANSACTION_FIELD.message_type = module.REQUEST_TRANSACTIONENTRY
module.REQUEST_TRANSACTION_FIELD.type = 11
module.REQUEST_TRANSACTION_FIELD.cpp_type = 10

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.sendTransaction.Request'
module.REQUEST.nested_types = {module.REQUEST_TRANSACTIONENTRY}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_TRANSACTION_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.sendTransaction.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = ''
module.RESULT_RESULT_FIELD.type = 9
module.RESULT_RESULT_FIELD.cpp_type = 9

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.sendTransaction.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Request.TransactionEntry = protobuf.Message(module.REQUEST_TRANSACTIONENTRY)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
