-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.REQUEST = protobuf.Descriptor()
module.REQUEST_T_ID_FIELD = protobuf.FieldDescriptor()
module.REQUEST_X_FIELD = protobuf.FieldDescriptor()
module.REQUEST_Y_FIELD = protobuf.FieldDescriptor()
module.REQUEST_DX_FIELD = protobuf.FieldDescriptor()
module.REQUEST_DY_FIELD = protobuf.FieldDescriptor()
module.RESULT = protobuf.Descriptor()
module.RESULT_RESULT_FIELD = protobuf.FieldDescriptor()

module.REQUEST_T_ID_FIELD.name = 't_id'
module.REQUEST_T_ID_FIELD.full_name = '.qlua.rpc.SetWindowPos.Request.t_id'
module.REQUEST_T_ID_FIELD.number = 1
module.REQUEST_T_ID_FIELD.index = 0
module.REQUEST_T_ID_FIELD.label = 1
module.REQUEST_T_ID_FIELD.has_default_value = false
module.REQUEST_T_ID_FIELD.default_value = 0
module.REQUEST_T_ID_FIELD.type = 5
module.REQUEST_T_ID_FIELD.cpp_type = 1

module.REQUEST_X_FIELD.name = 'x'
module.REQUEST_X_FIELD.full_name = '.qlua.rpc.SetWindowPos.Request.x'
module.REQUEST_X_FIELD.number = 2
module.REQUEST_X_FIELD.index = 1
module.REQUEST_X_FIELD.label = 1
module.REQUEST_X_FIELD.has_default_value = false
module.REQUEST_X_FIELD.default_value = 0
module.REQUEST_X_FIELD.type = 5
module.REQUEST_X_FIELD.cpp_type = 1

module.REQUEST_Y_FIELD.name = 'y'
module.REQUEST_Y_FIELD.full_name = '.qlua.rpc.SetWindowPos.Request.y'
module.REQUEST_Y_FIELD.number = 3
module.REQUEST_Y_FIELD.index = 2
module.REQUEST_Y_FIELD.label = 1
module.REQUEST_Y_FIELD.has_default_value = false
module.REQUEST_Y_FIELD.default_value = 0
module.REQUEST_Y_FIELD.type = 5
module.REQUEST_Y_FIELD.cpp_type = 1

module.REQUEST_DX_FIELD.name = 'dx'
module.REQUEST_DX_FIELD.full_name = '.qlua.rpc.SetWindowPos.Request.dx'
module.REQUEST_DX_FIELD.number = 4
module.REQUEST_DX_FIELD.index = 3
module.REQUEST_DX_FIELD.label = 1
module.REQUEST_DX_FIELD.has_default_value = false
module.REQUEST_DX_FIELD.default_value = 0
module.REQUEST_DX_FIELD.type = 5
module.REQUEST_DX_FIELD.cpp_type = 1

module.REQUEST_DY_FIELD.name = 'dy'
module.REQUEST_DY_FIELD.full_name = '.qlua.rpc.SetWindowPos.Request.dy'
module.REQUEST_DY_FIELD.number = 5
module.REQUEST_DY_FIELD.index = 4
module.REQUEST_DY_FIELD.label = 1
module.REQUEST_DY_FIELD.has_default_value = false
module.REQUEST_DY_FIELD.default_value = 0
module.REQUEST_DY_FIELD.type = 5
module.REQUEST_DY_FIELD.cpp_type = 1

module.REQUEST.name = 'Request'
module.REQUEST.full_name = '.qlua.rpc.SetWindowPos.Request'
module.REQUEST.nested_types = {}
module.REQUEST.enum_types = {}
module.REQUEST.fields = {module.REQUEST_T_ID_FIELD, module.REQUEST_X_FIELD, module.REQUEST_Y_FIELD, module.REQUEST_DX_FIELD, module.REQUEST_DY_FIELD}
module.REQUEST.is_extendable = false
module.REQUEST.extensions = {}
module.RESULT_RESULT_FIELD.name = 'result'
module.RESULT_RESULT_FIELD.full_name = '.qlua.rpc.SetWindowPos.Result.result'
module.RESULT_RESULT_FIELD.number = 1
module.RESULT_RESULT_FIELD.index = 0
module.RESULT_RESULT_FIELD.label = 1
module.RESULT_RESULT_FIELD.has_default_value = false
module.RESULT_RESULT_FIELD.default_value = false
module.RESULT_RESULT_FIELD.type = 8
module.RESULT_RESULT_FIELD.cpp_type = 7

module.RESULT.name = 'Result'
module.RESULT.full_name = '.qlua.rpc.SetWindowPos.Result'
module.RESULT.nested_types = {}
module.RESULT.enum_types = {}
module.RESULT.fields = {module.RESULT_RESULT_FIELD}
module.RESULT.is_extendable = false
module.RESULT.extensions = {}

module.Request = protobuf.Message(module.REQUEST)
module.Result = protobuf.Message(module.RESULT)


module.MESSAGE_TYPES = {'Request','Result'}
module.ENUM_TYPES = {}

return module
